import {
  AtSign,
  BarChart3,
  Bell,
  BookHeart,
  BookOpen,
  BookOpenCheck,
  Bot,
  Boxes,
  BrainCircuit,
  Building2,
  CalendarCheck,
  CalendarClock,
  Clock,
  Code2,
  Columns3,
  ContactRound,
  Database,
  FileOutput,
  FileSignature,
  FileText,
  Filter,
  FolderGit2,
  FolderTree,
  GitBranch,
  GitFork,
  Globe,
  Handshake,
  Hash,
  History,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Library,
  LifeBuoy,
  ListChecks,
  ListTodo,
  Lock,
  Mail,
  MailPlus,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  MousePointer,
  PanelRight,
  Paperclip,
  PieChart,
  Plug,
  Receipt,
  RefreshCw,
  Repeat,
  ScrollText,
  Search,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Split,
  StickyNote,
  Table2,
  Target,
  Terminal,
  Trash2,
  TrendingUp,
  Type,
  UserCheck,
  Users,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * The registries (products/data.ts, roles/data.ts) are pure data and name
 * their icons by key. This resolves a key to a lucide component, imported one
 * by one so the bundle carries only the icons the site uses.
 */
const ICONS: Record<string, LucideIcon> = {
  atSign: AtSign,
  barChart3: BarChart3,
  bell: Bell,
  bookHeart: BookHeart,
  bookOpen: BookOpen,
  bookOpenCheck: BookOpenCheck,
  bot: Bot,
  boxes: Boxes,
  brainCircuit: BrainCircuit,
  building2: Building2,
  calendarCheck: CalendarCheck,
  calendarClock: CalendarClock,
  clock: Clock,
  code2: Code2,
  columns3: Columns3,
  contactRound: ContactRound,
  database: Database,
  fileOutput: FileOutput,
  fileSignature: FileSignature,
  fileText: FileText,
  filter: Filter,
  folderGit2: FolderGit2,
  folderTree: FolderTree,
  gitBranch: GitBranch,
  gitFork: GitFork,
  globe: Globe,
  handshake: Handshake,
  hash: Hash,
  history: History,
  inbox: Inbox,
  keyRound: KeyRound,
  landmark: Landmark,
  layoutDashboard: LayoutDashboard,
  layoutGrid: LayoutGrid,
  layoutTemplate: LayoutTemplate,
  library: Library,
  lifeBuoy: LifeBuoy,
  listChecks: ListChecks,
  listTodo: ListTodo,
  lock: Lock,
  mail: Mail,
  mailPlus: MailPlus,
  megaphone: Megaphone,
  messageSquare: MessageSquare,
  messagesSquare: MessagesSquare,
  mousePointer: MousePointer,
  panelRight: PanelRight,
  paperclip: Paperclip,
  pieChart: PieChart,
  plug: Plug,
  receipt: Receipt,
  refreshCw: RefreshCw,
  repeat: Repeat,
  scrollText: ScrollText,
  search: Search,
  share2: Share2,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  split: Split,
  stickyNote: StickyNote,
  table2: Table2,
  target: Target,
  terminal: Terminal,
  trash2: Trash2,
  trendingUp: TrendingUp,
  type: Type,
  userCheck: UserCheck,
  users: Users,
  webhook: Webhook,
  workflow: Workflow,
  zap: Zap,
};

export function iconFor(key: string): LucideIcon {
  return ICONS[key] ?? Sparkles;
}
