import { STATIC_TOOLS } from "../../../mcp/toolManifest.js";

/**
 * The searchable view of the genosyn tool catalogue: which domain each tool
 * belongs to, and the words an operator would actually use to ask for it.
 *
 * ## Why this is a view and not a manifest field
 *
 * `mcp/protocol.ts` re-projects only `{name, description, inputSchema}` when it
 * answers `tools/list`, but `routes/mcpInternal.ts` serves `STATIC_TOOLS` raw
 * from `/manifest`. So a new field on {@link McpToolSpec} would leak to external
 * MCP clients through one path while staying invisible on the other — a
 * published contract change nobody asked for. Keying by name from beside the
 * agent costs one assertion and changes no contract.
 *
 * ## Why hand-curated keywords
 *
 * Ranking on descriptions alone does not work on this corpus, and that is
 * measurable rather than suspected: "spreadsheet" matches none of the 104
 * tools, "database" matches only `run_chart`, and "invoice" matches fourteen —
 * mostly Base tools that happen to use invoices as a worked example. A model
 * asking for "the spreadsheet thing" would be told it has no such tool while
 * `base_rows` sat one synonym away.
 *
 * So the keyword layer is the retrieval surface, and `discovery.test.ts` is its
 * regression gate. Add a keyword when a plausible phrasing misses; do not
 * delete one because it looks redundant.
 */

export type ToolDomain = {
  /** Human-facing label, used in the prompt and in `find_tools`' footer. */
  label: string;
  /** One line on what the domain is for. */
  blurb: string;
  /** Manifest tool names in this domain. */
  tools: string[];
};

export const TOOL_DOMAINS: Record<string, ToolDomain> = {
  orientation: {
    label: "orientation",
    blurb: "Find out who you are and who else works here.",
    tools: ["get_self", "list_employees", "list_teams"],
  },
  routines: {
    label: "routines",
    blurb: "Scheduled recurring AI work. Never call these tasks.",
    tools: ["list_routines", "get_routine", "create_routine", "update_routine", "delete_routine"],
  },
  runs: {
    label: "runs",
    blurb:
      "The record of scheduled work: what each Run did, how it was graded, and the evidence behind the verdict.",
    tools: ["list_runs", "get_run_report"],
  },
  goals: {
    label: "goals",
    blurb: "The company's measurable objectives.",
    tools: ["list_goals", "get_goal", "update_goal_progress"],
  },
  improvement: {
    label: "improvement",
    blurb: "Stage edits to your own surfaces, or propose new standing work, for a human to apply.",
    tools: ["propose_revision", "propose_initiative"],
  },
  continuity: {
    label: "continuity",
    blurb: "Carry work across sessions: wake yourself later, keep state between Runs.",
    tools: [
      "schedule_wakeup",
      "cancel_wakeup",
      "create_workstream",
      "update_workstream",
      "list_workstreams",
    ],
  },
  pipelines: {
    label: "pipelines",
    blurb:
      "Deterministic trigger-to-step automation. No model in the loop; never call these routines.",
    tools: [
      "list_pipelines",
      "get_pipeline",
      "list_pipeline_node_types",
      "create_pipeline",
      "update_pipeline",
      "delete_pipeline",
      "run_pipeline",
      "list_pipeline_runs",
      "get_pipeline_run",
      "rotate_pipeline_webhook_token",
    ],
  },
  projects: {
    label: "projects & todos",
    blurb: "One-off work items for humans and AI employees.",
    tools: ["list_projects", "create_project", "list_todos", "create_todo", "update_todo"],
  },
  meetings: {
    label: "meetings",
    blurb: "Recorded calls, attendees, and what was said.",
    tools: ["list_meetings", "get_meeting", "get_meeting_transcript", "start_notetaker"],
  },
  decisions: {
    label: "decisions",
    blurb: "Ask a human to choose, and read back what they chose.",
    tools: ["request_decision", "list_decisions", "cancel_decision", "decide_decision"],
  },
  journal: {
    label: "journal",
    blurb: "Your own diary. The last week is auto-injected into every prompt.",
    tools: ["list_journal", "add_journal_entry"],
  },
  memory: {
    label: "memory",
    blurb: "Durable facts about yourself, auto-injected into every prompt.",
    tools: ["list_memory", "add_memory", "update_memory", "delete_memory"],
  },
  skills: {
    label: "skills",
    blurb: "The Skill playbooks attached to an AI employee.",
    tools: ["list_skills", "create_skill", "update_skill", "delete_skill"],
  },
  bases: {
    label: "bases",
    blurb: "The structured data store — bases, tables, fields and rows.",
    tools: [
      "list_bases",
      "get_base",
      "create_base",
      "create_base_table",
      "update_base_table",
      "delete_base_table",
      "add_base_field",
      "update_base_field",
      "delete_base_field",
      "list_base_rows",
      "create_base_row",
      "update_base_row",
      "delete_base_row",
    ],
  },
  base_records: {
    label: "base records",
    blurb: "One row of a Base, with its comment thread and attached files.",
    tools: [
      "get_base_record",
      "list_record_comments",
      "create_record_comment",
      "delete_record_comment",
      "list_record_attachments",
      "attach_file_to_record",
      "read_record_attachment",
      "delete_record_attachment",
    ],
  },
  notes: {
    label: "notes",
    blurb: "The company's long-form pages and notebooks.",
    tools: [
      "list_notebooks",
      "list_notes",
      "search_notes",
      "get_note",
      "create_note",
      "update_note",
      "delete_note",
    ],
  },
  resources: {
    label: "resources",
    blurb: "The company's reference library of ingested documents.",
    tools: [
      "list_resources",
      "search_resources",
      "get_resource",
      "export_resource",
      "create_resource",
      "update_resource",
      "delete_resource",
    ],
  },
  vault: {
    label: "Vault",
    blurb:
      "Use granted passwords, TOTP codes, and software passkeys without putting authenticator material in model context; create generated logins safely.",
    tools: ["list_vault_items", "create_vault_login", "update_vault_login"],
  },
  signing: {
    label: "document signing",
    blurb:
      "Prepare, send, track, remind and void signature envelopes. Needs a Signing Grant; recipients alone consent and sign.",
    tools: [
      "list_signature_envelopes",
      "get_signature_envelope",
      "draft_signature_envelope",
      "send_signature_envelope",
      "remind_signature_recipient",
      "void_signature_envelope",
    ],
  },
  charts: {
    label: "Explore data & charts",
    blurb: "Granted databases and saved SQL charts.",
    tools: [
      "list_explore_connections",
      "get_explore_schema",
      "run_explore_query",
      "list_charts",
      "get_chart",
      "run_chart",
      "create_chart",
      "update_chart",
      "delete_chart",
    ],
  },
  dashboards: {
    label: "dashboards",
    blurb: "Dashboards assembled out of saved charts.",
    tools: ["list_dashboards", "get_dashboard", "create_dashboard", "add_dashboard_card"],
  },
  workspace: {
    label: "workspace chat",
    blurb: "Company channels and the messages in them.",
    tools: [
      "list_workspace_channels",
      "create_workspace_channel",
      "rename_workspace_channel",
      "archive_workspace_channel",
      "send_workspace_message",
    ],
  },
  handoffs: {
    label: "handoffs",
    blurb: "Hand work to a teammate, and resolve handoffs sent to you.",
    tools: [
      "list_handoffs",
      "create_handoff",
      "complete_handoff",
      "decline_handoff",
      "cancel_handoff",
    ],
  },
  mail: {
    label: "mail",
    blurb: "The company's Gmail mailboxes. Needs a per-mailbox grant.",
    tools: [
      "list_mail_accounts",
      "search_mail",
      "get_mail_thread",
      "read_mail_attachment",
      "create_mail_draft",
      "edit_mail_draft",
      "update_mail_thread",
      "send_mail",
      "suggest_mail_actions",
    ],
  },
  finance: {
    label: "finance",
    blurb:
      "Estimates, one-off and recurring invoices, customers, payments and the books. Needs a finance grant.",
    tools: [
      "list_finance_accounts",
      "list_finance_transactions",
      "get_finance_transaction",
      "review_finance_transaction",
      "get_finance_report",
      "list_invoices",
      "get_invoice",
      "list_recurring_invoices",
      "get_recurring_invoice",
      "list_customers",
      "get_customer",
      "create_customer",
      "update_customer",
      "create_estimate",
      "create_invoice",
      "create_recurring_invoice",
      "update_recurring_invoice",
      "send_invoice",
      "record_payment",
      "void_invoice",
    ],
  },
  revenue: {
    label: "revenue",
    blurb:
      "Follow-ups, Accounts, Contacts, Deals, Partnerships, imports, bulk jobs, history, exports, evidence and data quality. Needs a Revenue Grant.",
    tools: [
      "list_follow_ups",
      "create_follow_up",
      "update_follow_up",
      "list_follow_up_views",
      "create_follow_up_view",
      "update_follow_up_view",
      "delete_follow_up_view",
      "list_revenue_accounts",
      "create_revenue_account",
      "get_revenue_account",
      "update_revenue_account",
      "archive_revenue_account",
      "merge_revenue_accounts",
      "list_contacts",
      "search_contacts",
      "get_contact",
      "get_contact_timeline",
      "list_activities",
      "get_activity",
      "update_activity",
      "delete_activity",
      "export_activities",
      "list_deals",
      "get_deal",
      "get_deal_board",
      "list_deal_stages",
      "create_deal_stage",
      "update_deal_stage",
      "reorder_deal_stages",
      "archive_deal_stage",
      "list_sequences",
      "get_sequence",
      "create_sequence",
      "update_sequence",
      "replace_sequence_steps",
      "archive_sequence",
      "list_signals",
      "get_signal",
      "create_signal",
      "update_signal",
      "list_signal_events",
      "test_signal",
      "archive_signal",
      "restore_signal",
      "get_revenue_report",
      "create_contact",
      "update_contact",
      "create_deal",
      "update_deal",
      "move_deal_stage",
      "log_activity",
      "add_deal_contact",
      "enroll_in_sequence",
      "suppress_email",
      "list_revenue_classifications",
      "create_revenue_classification",
      "update_revenue_classification",
      "list_revenue_custom_fields",
      "create_revenue_custom_field",
      "update_revenue_custom_field",
      "install_base_migration_custom_fields",
      "set_revenue_custom_fields",
      "list_partnerships",
      "get_partnership",
      "create_partnership",
      "update_partnership",
      "add_partnership_contact",
      "list_revenue_documents",
      "link_revenue_document",
      "get_revenue_document",
      "update_revenue_document",
      "delete_revenue_document",
      "download_revenue_document",
      "list_revenue_imports",
      "get_revenue_import",
      "preview_base_revenue_import",
      "run_base_revenue_import",
      "preview_linked_base_revenue_import",
      "run_linked_base_revenue_import",
      "preview_revenue_rows_import",
      "run_revenue_rows_import",
      "preview_linked_revenue_rows_import",
      "run_linked_revenue_rows_import",
      "migrate_base_revenue_attachments",
      "rollback_revenue_import",
      "list_revenue_import_rows",
      "export_revenue_import_reconciliation",
      "preview_revenue_record_merge",
      "merge_revenue_records",
      "resolve_revenue_record_redirect",
      "list_revenue_operations",
      "get_revenue_operation",
      "undo_revenue_operation",
      "preview_revenue_bulk_operation",
      "start_revenue_bulk_job",
      "get_revenue_bulk_job",
      "export_revenue_bulk_reconciliation",
      "preview_historical_deal_import",
      "run_historical_deal_import",
      "list_deal_history",
      "list_deal_history_coverage",
      "preview_deal_history_backfill",
      "backfill_deal_history",
      "export_revenue_snapshot",
      "propose_revenue_account_domains",
      "list_commercial_value_backlog",
      "propose_finance_commercial_values",
      "propose_stripe_commercial_values",
      "create_commercial_value_proposal",
      "list_revenue_field_evidence",
      "review_revenue_field_evidence",
      "scan_revenue_duplicates",
      "list_revenue_duplicate_candidates",
      "dismiss_revenue_duplicate_candidate",
      "scan_revenue_mail_documents",
      "list_revenue_document_candidates",
      "review_revenue_document_candidate",
    ],
  },
  marketing: {
    label: "marketing agency",
    blurb:
      "Paid Campaign strategy, Creative, Experiments and performance. Needs a Marketing grant; external ad platforms need Connection Grants.",
    tools: [
      "get_marketing_overview",
      "list_marketing_campaigns",
      "get_marketing_campaign",
      "create_marketing_campaign",
      "update_marketing_campaign",
      "list_marketing_creatives",
      "create_marketing_creative",
      "update_marketing_creative",
      "list_marketing_experiments",
      "create_marketing_experiment",
      "update_marketing_experiment",
      "record_marketing_performance",
    ],
  },
  files: {
    label: "files",
    blurb:
      "Send a file, work on PDF forms, read, edit or write Word documents, and convert one to PDF.",
    tools: [
      "send_chat_attachment",
      "read_pdf_fields",
      "fill_pdf_form",
      "read_pdf_layout",
      "overlay_pdf_text",
      "read_docx",
      "edit_docx",
      "create_docx",
      "convert_to_pdf",
    ],
  },
  web: {
    label: "web",
    blurb: "Search the web, read a page, download a file to work on.",
    tools: ["search_web", "fetch_web_page", "download_web_file"],
  },
  repositories: {
    label: "repositories",
    blurb:
      "The Repositories granted to you — code, documents, anything version-controlled. Changing one means starting a work session first; the repository_* tools work only inside one, where you can also run the repository's tests and linter before you commit.",
    tools: [
      "list_repositories",
      "start_repository_work_session",
      "repository_list_files",
      "repository_read_file",
      "repository_write_file",
      "repository_edit_file",
      "repository_delete_file",
      "repository_search",
      "repository_glob",
      "repository_status",
      "repository_diff",
      "repository_update_steps",
      "repository_run_command",
      "repository_commit",
    ],
  },
};

/**
 * Words that should find a tool but do not appear in its description.
 *
 * Every entry here is a miss someone actually hit, or would have. Keep the
 * vocabulary an operator would type, not the vocabulary the code uses.
 */
export const TOOL_KEYWORDS: Record<string, string[]> = {
  // Nothing in the meeting tools' prose says "call", "zoom" or "notes", which
  // is what somebody actually types when they want them.
  list_meetings: [
    "call",
    "calls",
    "zoom",
    "google meet",
    "teams",
    "recording",
    "notetaker",
    "calendar",
  ],
  get_meeting: ["call", "notes", "minutes", "recap", "attendees", "who was on the call"],
  get_meeting_transcript: [
    "transcript",
    "what was said",
    "what did we discuss",
    "discussed",
    "quote",
    "recording",
    "minutes",
    "verbatim",
  ],
  start_notetaker: [
    "join call",
    "join meeting",
    "record call",
    "take notes",
    "notetaker",
    "google meet",
  ],
  // Bases are the worst offender: nothing in their prose says "spreadsheet".
  list_bases: ["spreadsheet", "table", "grid", "database", "dataset"],
  get_base: ["spreadsheet", "table", "grid", "schema"],
  create_base: ["spreadsheet", "table", "grid", "new database", "tracker"],
  create_base_table: ["spreadsheet", "tab", "sheet", "worksheet"],
  update_base_table: ["rename table", "sheet"],
  delete_base_table: ["drop table", "sheet"],
  add_base_field: ["column", "field", "property", "add column"],
  update_base_field: ["column", "rename column", "select options", "dropdown"],
  delete_base_field: ["column", "drop column"],
  list_base_rows: [
    "rows",
    "records",
    "query",
    "database",
    "sql",
    "filter",
    "spreadsheet",
    "read data",
  ],
  create_base_row: ["row", "record", "entry", "add data", "insert"],
  update_base_row: ["row", "record", "edit data", "cell"],
  delete_base_row: ["row", "record", "remove data"],
  get_base_record: ["row", "record", "detail"],
  list_record_comments: ["comment", "thread", "discussion", "note on a row"],
  create_record_comment: ["comment", "reply on a record"],
  delete_record_comment: ["comment"],
  list_record_attachments: ["file", "attachment", "upload", "document"],
  attach_file_to_record: ["file", "attachment", "upload", "attach"],
  read_record_attachment: ["file", "attachment", "download", "open file"],
  delete_record_attachment: ["file", "attachment"],

  // Charts / dashboards — "sql" and "report" never appear together in prose.
  list_explore_connections: [
    "database connection",
    "data source",
    "warehouse",
    "postgres",
    "mysql",
    "clickhouse",
  ],
  get_explore_schema: ["database schema", "tables", "columns", "inspect database"],
  run_explore_query: ["sql", "query database", "ad hoc query", "explore data", "analyze data"],
  run_chart: ["sql", "query", "database", "report", "numbers", "metrics"],
  list_charts: ["sql", "report", "graph", "metrics"],
  get_chart: ["sql", "graph", "report"],
  create_chart: ["sql", "graph", "report", "visualise", "visualize"],
  update_chart: ["sql", "graph"],
  delete_chart: ["graph"],
  list_dashboards: ["report", "overview", "kpi"],
  get_dashboard: ["report", "kpi"],
  create_dashboard: ["report", "kpi", "overview"],
  add_dashboard_card: ["report", "tile", "widget", "panel"],

  // Mail — operators say "inbox" and "reply", the prose says "thread".
  list_mail_accounts: ["inbox", "mailbox", "gmail", "email account"],
  search_mail: ["inbox", "email", "gmail", "find message", "search inbox"],
  get_mail_thread: ["inbox", "email", "read email", "conversation"],
  read_mail_attachment: [
    "attachment",
    "email attachment",
    "open the attached file",
    "the pdf they sent",
    "form attached to the email",
  ],
  create_mail_draft: ["email", "compose", "write email", "reply", "draft"],
  edit_mail_draft: ["email", "revise draft", "amend"],
  update_mail_thread: ["archive email", "label", "mark read", "inbox"],
  send_mail: ["email", "reply", "send email", "respond"],
  suggest_mail_actions: ["inbox", "triage", "what should i do with this email"],

  // Finance — "who owes us money" is the query, "receivable" is the word.
  list_invoices: ["receivable", "billing", "who owes us", "unpaid", "outstanding", "ar"],
  get_invoice: ["receivable", "billing", "bill"],
  list_recurring_invoices: [
    "recurring billing",
    "automatic invoice",
    "repeat invoice",
    "subscription billing",
    "annual renewal",
  ],
  get_recurring_invoice: ["recurring billing", "invoice schedule", "renewal schedule"],
  create_estimate: ["quote", "quotation", "proposal", "pricing", "raise an estimate"],
  create_invoice: ["bill", "billing", "charge", "receivable", "raise an invoice"],
  create_recurring_invoice: [
    "recurring billing",
    "automatic invoice",
    "repeat invoice",
    "subscription billing",
    "annual renewal",
  ],
  update_recurring_invoice: [
    "pause invoice schedule",
    "resume invoice schedule",
    "end invoice schedule",
    "change recurring billing",
  ],
  send_invoice: ["bill", "billing", "email invoice", "chase"],
  record_payment: ["paid", "payment", "receipt", "mark paid", "settle"],
  void_invoice: ["cancel invoice", "write off"],
  list_customers: ["client", "account", "buyer", "crm"],
  get_customer: ["client", "account", "buyer"],
  create_customer: ["client", "account", "new client"],
  update_customer: ["client", "account"],
  list_finance_accounts: ["ledger", "books", "chart of accounts", "bank"],
  list_finance_transactions: ["ledger", "books", "bank", "spend", "expenses", "transactions"],
  get_finance_transaction: ["ledger", "books", "expense"],
  review_finance_transaction: [
    "ledger",
    "books",
    "approve",
    "categorise",
    "categorize",
    "reconcile",
  ],
  get_finance_report: ["p&l", "profit", "loss", "balance sheet", "books", "financials"],

  // Revenue — the CRM half of the money. Finance answers "who owes us"; this
  // answers "who are we talking to", and none of that vocabulary — pipeline,
  // lead, prospect, churn, cadence — appears in the finance prose. "client" is
  // deliberately absent: it belongs to `create_customer`, and duplicating it
  // here would put two plausible tools on the same query.
  list_follow_ups: [
    "sales queue",
    "overdue",
    "reminder",
    "next action",
    "due today",
    "unassigned follow ups",
    "follow ups by assignee",
    "urgent follow ups",
    "overdue age",
    "follow ups by deal stage",
    "follow ups by account status",
    "archived follow ups",
    "search follow ups",
  ],
  create_follow_up: ["sales task", "reminder", "next action", "call back", "due date"],
  update_follow_up: ["complete follow-up", "reschedule", "mark done", "sales task"],
  list_follow_up_views: ["saved views", "saved filters", "triage views"],
  create_follow_up_view: ["save filter", "saved view", "shared queue"],
  update_follow_up_view: ["edit saved view", "rename filter", "reorder view"],
  delete_follow_up_view: ["delete saved view", "remove filter"],
  list_revenue_accounts: ["crm", "prospect companies", "organisations", "organizations"],
  create_revenue_account: ["new prospect company", "crm account", "organisation", "organization"],
  get_revenue_account: ["prospect company", "account history", "company crm"],
  update_revenue_account: ["qualify account", "prospect company", "account owner"],
  archive_revenue_account: ["archive account", "restore account", "hide company"],
  merge_revenue_accounts: ["merge accounts", "duplicate company", "combine accounts"],
  list_contacts: ["crm", "leads", "prospects", "contacts"],
  search_contacts: ["crm", "lead", "prospect", "find a person", "find someone"],
  get_contact: ["lead", "prospect", "person"],
  get_contact_timeline: ["history", "timeline", "what happened with", "last spoke"],
  list_activities: ["activity audit", "company activity", "search timeline"],
  get_activity: ["activity id", "timeline record"],
  update_activity: ["correct activity", "edit call", "fix note"],
  delete_activity: ["remove activity", "delete note", "cleanup timeline"],
  export_activities: ["activity export", "crm csv", "audit export"],
  list_deals: ["pipeline", "opportunities", "deals in flight"],
  get_deal: ["opportunity", "pipeline"],
  get_deal_board: ["pipeline", "board", "kanban", "what is in the pipeline"],
  list_deal_stages: ["pipeline", "stages", "sales process"],
  create_deal_stage: ["custom stage", "sales process", "new stage"],
  update_deal_stage: ["stage probability", "rename stage", "sales process"],
  reorder_deal_stages: ["stage order", "sales process"],
  archive_deal_stage: ["remove stage", "retire stage"],
  list_sequences: ["campaign", "outbound", "drip", "cadence"],
  get_sequence: ["campaign details", "sequence steps", "cadence"],
  create_sequence: ["new outbound sequence", "create campaign", "cadence"],
  update_sequence: ["edit campaign", "sequence settings", "pause outbound"],
  replace_sequence_steps: ["sequence steps", "outbound ladder", "cadence"],
  archive_sequence: ["retire campaign", "stop sequence"],
  list_signals: ["trigger", "product usage", "churn risk", "intent"],
  get_signal: ["signal query", "trigger config", "product usage"],
  create_signal: ["new product signal", "usage trigger"],
  update_signal: ["edit product signal", "trigger action"],
  list_signal_events: ["signal history", "trigger runs", "execution history"],
  test_signal: ["dry run signal", "test trigger query"],
  archive_signal: ["disable signal", "retire trigger"],
  restore_signal: ["unarchive signal", "restore trigger"],
  get_revenue_report: ["mrr", "arr", "churn", "retention", "funnel", "win rate", "cac"],
  create_contact: ["new lead", "capture a lead", "add a contact"],
  update_contact: ["enrich a contact", "lifecycle stage"],
  create_deal: ["new opportunity", "open a deal", "pipeline"],
  update_deal: ["deal amount", "next step"],
  move_deal_stage: ["close won", "closed lost", "advance the deal", "mark won"],
  log_activity: ["log a call", "log a meeting", "log a note", "meeting notes"],
  add_deal_contact: ["buying committee", "stakeholder", "champion"],
  enroll_in_sequence: ["outbound", "campaign", "enroll", "cadence"],
  suppress_email: ["unsubscribe", "do not contact", "opt out", "suppression list"],
  list_revenue_classifications: [
    "deal sources",
    "buying roles",
    "partnership types",
    "controlled values",
  ],
  create_revenue_classification: ["add deal source", "buying role", "controlled value"],
  update_revenue_classification: ["rename deal source", "archive controlled value"],
  list_revenue_custom_fields: ["crm schema", "custom properties", "extra fields"],
  create_revenue_custom_field: ["new crm field", "custom property", "crm schema"],
  update_revenue_custom_field: ["edit crm field", "custom property"],
  install_base_migration_custom_fields: ["crm migration fields", "base migration setup"],
  set_revenue_custom_fields: [
    "crm properties",
    "plan interest",
    "competitor",
    "qualification fields",
    "custom field provenance",
    "write field evidence",
    "source confidence",
    "observed verified value",
  ],
  list_partnerships: ["partners", "alliances", "channel relationships"],
  get_partnership: ["partner contacts", "alliance", "channel relationship"],
  create_partnership: ["new partner", "alliance", "channel relationship"],
  update_partnership: ["partner follow-up", "alliance status", "partner owner"],
  add_partnership_contact: ["partner stakeholder", "reply all", "primary partner contact"],
  list_revenue_documents: ["proposal", "rfp", "contract", "security questionnaire", "attachments"],
  link_revenue_document: ["attach proposal", "link contract", "rfp", "security questionnaire"],
  get_revenue_document: ["document metadata", "proposal", "contract"],
  update_revenue_document: ["edit document", "rename proposal", "document metadata"],
  delete_revenue_document: ["unlink document", "remove proposal"],
  download_revenue_document: ["download proposal", "fetch contract", "document bytes"],
  list_revenue_imports: [
    "import history",
    "migration reports",
    "crm reconciliation",
    "import summary list",
  ],
  get_revenue_import: [
    "import report",
    "migration reconciliation",
    "import summary counts",
    "compact import header",
  ],
  preview_base_revenue_import: ["migrate crm", "dry run", "duplicate preview", "base import"],
  run_base_revenue_import: ["migrate crm", "bulk import", "base migration"],
  preview_linked_base_revenue_import: [
    "atomic crm migration",
    "split base rows",
    "account contact deal",
    "split legacy crm rows into accounts contacts and deals",
  ],
  run_linked_base_revenue_import: ["atomic crm migration", "split base rows", "linked import"],
  preview_revenue_rows_import: [
    "csv import",
    "json import",
    "external crm import",
    "connector import preview",
    "raw rows migration",
  ],
  run_revenue_rows_import: [
    "import csv rows",
    "import json rows",
    "connector migration",
    "external crm migration",
  ],
  preview_linked_revenue_rows_import: [
    "linked csv import",
    "linked json import",
    "split external crm rows",
  ],
  run_linked_revenue_rows_import: [
    "linked external crm migration",
    "atomic csv crm import",
    "atomic json crm import",
  ],
  migrate_base_revenue_attachments: [
    "base attachments",
    "migrate crm documents",
    "attachment import",
  ],
  rollback_revenue_import: ["undo crm import", "revert migration", "import rollback"],
  list_revenue_import_rows: [
    "import row decisions",
    "migration errors",
    "source id lookup",
    "native id lookup",
    "import json reconciliation",
    "direct source row lookup",
  ],
  export_revenue_import_reconciliation: [
    "import csv",
    "failed import rows",
    "skipped import rows",
    "duplicate import rows",
  ],
  preview_revenue_record_merge: [
    "merge preview",
    "conflict resolution",
    "duplicate preview",
    "choose merge survivor",
  ],
  merge_revenue_records: [
    "merge duplicate candidate",
    "merge reviewed duplicate",
    "merge accounts",
    "merge contacts",
    "merge deals",
    "merge partnerships",
    "combine duplicate",
  ],
  resolve_revenue_record_redirect: [
    "tombstone",
    "old record id",
    "merged record redirect",
    "alias lookup",
  ],
  list_revenue_operations: [
    "merge audit",
    "bulk audit",
    "historical import audit",
    "revenue jobs",
    "operation history",
    "rollback state",
  ],
  get_revenue_operation: [
    "merge audit rows",
    "bulk reconciliation",
    "historical import rows",
    "operation detail",
    "before after audit",
  ],
  undo_revenue_operation: [
    "undo merge",
    "undo bulk job",
    "rollback bulk",
    "undo historical deal import",
    "revert revenue job",
  ],
  preview_revenue_bulk_operation: [
    "bulk preview",
    "mass update",
    "validate selection",
    "bulk triage",
    "frozen selection",
    "preview archive contacts",
    "preview archive deals",
    "preview archive partnerships",
    "preview restore contacts",
    "bulk complete follow ups",
    "bulk reschedule follow ups",
    "bulk reassign follow ups",
  ],
  start_revenue_bulk_job: [
    "bulk job",
    "mass update",
    "asynchronous revenue update",
    "bulk stage move",
    "atomic bulk update",
    "partial failure bulk",
    "idempotent bulk job",
    "archive contacts",
    "archive deals",
    "archive partnerships",
    "restore contacts",
    "restore deals",
    "restore partnerships",
    "bulk follow up triage",
  ],
  get_revenue_bulk_job: [
    "bulk progress",
    "job status",
    "reconciliation rows",
    "bulk json results",
    "per record validation",
  ],
  export_revenue_bulk_reconciliation: ["bulk reconciliation csv", "bulk errors", "job results"],
  preview_historical_deal_import: [
    "historical deal events",
    "stage history import",
    "sales cycle migration",
    "original deal creation date",
    "historical owner changes",
    "historical amount changes",
    "lost reason history",
    "effective timestamp",
    "history completeness",
    "source event id",
  ],
  run_historical_deal_import: [
    "import deal history",
    "stage transitions",
    "original close date",
    "original won date",
    "original lost date",
    "historical conversion",
    "historical sales cycle",
  ],
  list_deal_history: [
    "deal event history",
    "time in stage",
    "sales velocity",
    "conversion history",
  ],
  list_deal_history_coverage: [
    "missing deal history",
    "history coverage",
    "migrated deals without history",
    "history completeness inventory",
  ],
  preview_deal_history_backfill: [
    "preview activity backfill",
    "safe deal history repair",
    "migration snapshot preview",
  ],
  backfill_deal_history: ["reconstruct deal history", "activity backfill", "sales cycle"],
  export_revenue_snapshot: [
    "crm export",
    "revenue json",
    "revenue csv",
    "complete snapshot",
    "export accounts",
    "export contacts",
    "export deals",
    "export partnerships",
    "export partnership contacts",
    "export buying committees",
    "export follow ups",
    "export revenue documents",
    "export deal stages",
    "export custom field definitions",
    "export custom field values",
    "export import reconciliation",
    "export deal history",
    "export field evidence",
    "export duplicate candidates",
    "export revenue audit",
    "export gmail document candidates",
  ],
  propose_revenue_account_domains: [
    "canonical domain",
    "website enrichment",
    "domain candidates",
    "account matching",
    "website redirect",
    "domain alias",
    "subdomain resolution",
    "disposable email domain",
    "public email domain",
    "domain confidence",
    "domain collision",
  ],
  list_commercial_value_backlog: [
    "zero value deals",
    "commercial value backlog",
    "deal value candidates",
    "missing deal amount",
    "ambiguous account value",
  ],
  propose_finance_commercial_values: [
    "reconcile deal value",
    "invoice evidence",
    "finance acv",
    "payments to deal value",
    "zero value deal",
  ],
  propose_stripe_commercial_values: [
    "stripe deal value",
    "subscription arr",
    "commercial reconciliation",
    "stripe invoice evidence",
    "zero value deal",
  ],
  create_commercial_value_proposal: ["proposal value", "confirmed terms", "mrr arr acv tcv"],
  list_revenue_field_evidence: [
    "field provenance",
    "enrichment evidence",
    "verification history",
    "superseded values",
  ],
  review_revenue_field_evidence: [
    "approve enrichment",
    "verify field",
    "accept evidence",
    "supersede value",
  ],
  scan_revenue_duplicates: [
    "duplicate detection",
    "canonical domain duplicates",
    "alias domain duplicates",
    "contact email duplicates",
    "stripe finance identifier duplicates",
    "similar deal titles",
    "find duplicate contacts",
    "find duplicate deals",
  ],
  list_revenue_duplicate_candidates: [
    "duplicate queue",
    "matching confidence",
    "duplicate evidence",
    "explain duplicate match",
    "review duplicate candidates",
  ],
  dismiss_revenue_duplicate_candidate: ["not a duplicate", "dismiss match", "duplicate memory"],
  scan_revenue_mail_documents: [
    "gmail attachments",
    "capture proposals",
    "historical email backfill",
    "gmail attachment id deduplication",
    "gmail file hash deduplication",
    "classify gmail documents",
    "gmail message provenance",
  ],
  list_revenue_document_candidates: [
    "attachment review queue",
    "gmail document matching",
    "proposal candidates",
    "gmail attachment candidates",
    "gmail thread provenance",
  ],
  review_revenue_document_candidate: [
    "approve attachment",
    "link gmail document",
    "reject attachment",
  ],

  // Marketing agency
  get_marketing_overview: ["ads dashboard", "paid media", "ad agency", "campaign performance"],
  list_marketing_campaigns: ["ads", "paid media", "campaign briefs", "media plan"],
  get_marketing_campaign: ["ad brief", "campaign strategy", "paid acquisition"],
  create_marketing_campaign: ["new ad campaign", "media plan", "paid campaign"],
  update_marketing_campaign: ["launch campaign", "pause campaign", "campaign strategy"],
  list_marketing_creatives: ["ad copy", "assets", "variants", "creative review"],
  create_marketing_creative: ["write ad", "ad copy", "creative variant", "concept"],
  update_marketing_creative: ["approve ad", "revise copy", "retire creative"],
  list_marketing_experiments: ["ab test", "split test", "creative test"],
  create_marketing_experiment: [
    "ab test",
    "split test",
    "hypothesis",
    "compare ad creative variants",
  ],
  update_marketing_experiment: ["pick winner", "decide test", "stop experiment"],
  record_marketing_performance: [
    "settled ad spend",
    "impressions",
    "clicks",
    "conversions",
    "roas",
  ],

  // Notes / resources — "doc", "page" and "wiki" are the words in use.
  list_notes: ["doc", "document", "page", "wiki"],
  search_notes: ["doc", "document", "page", "wiki", "find a doc"],
  get_note: ["doc", "document", "page", "wiki", "read a doc"],
  create_note: ["doc", "document", "page", "wiki", "write up"],
  update_note: ["doc", "document", "page", "edit doc"],
  delete_note: ["doc", "document", "page"],
  list_notebooks: ["doc", "wiki", "folder"],
  list_resources: ["knowledge", "library", "reference", "pdf", "upload"],
  search_resources: ["knowledge", "library", "reference", "look up", "rag"],
  get_resource: ["knowledge", "library", "reference", "read"],
  export_resource: ["knowledge", "download", "export"],
  create_resource: [
    "knowledge",
    "library",
    "ingest",
    "upload",
    "file a document",
    "add to resources",
    "save the attachment",
    "pdf resource",
  ],
  update_resource: ["knowledge", "library"],
  delete_resource: ["knowledge", "library"],

  // Vault — password-manager and credential language should converge on the
  // product surface without teaching the model to request plaintext.
  list_vault_items: [
    "password manager",
    "credentials",
    "login",
    "sign in",
    "api key",
    "secure note",
    "totp",
    "2fa",
    "two factor code",
    "authenticator code",
    "one time password",
    "passkey",
    "webauthn",
  ],
  create_vault_login: [
    "generate password",
    "save login",
    "new credentials",
    "create account password",
    "complete signup",
    "prepare authenticator enrollment",
    "set up two factor authentication",
    "save totp",
    "register passkey",
    "create software passkey",
  ],
  update_vault_login: ["rename login", "change username", "update login context"],

  // Signing — operators will usually say contract, agreement, e-signature,
  // or the incumbent product name rather than "signature envelope".
  list_signature_envelopes: [
    "contract status",
    "agreement status",
    "signature requests",
    "awaiting signature",
    "unsigned documents",
    "docusign",
  ],
  get_signature_envelope: [
    "inspect contract",
    "read agreement",
    "review signature request",
    "signature request readiness",
    "ready to send",
    "signature progress",
    "signers",
    "e-signature",
  ],
  draft_signature_envelope: [
    "prepare contract for signature",
    "prepare agreement",
    "create signature request",
    "add signature fields",
    "e-signature",
    "docusign",
  ],
  send_signature_envelope: [
    "send contract for signature",
    "send agreement for signature",
    "request signatures",
    "dispatch signature request",
    "e-signature",
  ],
  remind_signature_recipient: [
    "chase signature",
    "signature reminder",
    "remind signer",
    "nudge signer",
    "resend signing link",
  ],
  void_signature_envelope: [
    "cancel signature request",
    "withdraw contract",
    "revoke signing link",
    "void agreement",
  ],

  // Files
  send_chat_attachment: ["file", "download", "attach", "send file", "deliver"],
  read_pdf_fields: ["pdf", "form", "fields"],
  fill_pdf_form: ["pdf", "form", "complete form", "fill in"],
  // A form with no fields is the case people describe, not the cause — so the
  // words they reach for are about the paper, not the AcroForm.
  read_pdf_layout: [
    "pdf",
    "form",
    "layout",
    "where on the page",
    "coordinates",
    "scanned form",
    "non-fillable",
    "read the page",
  ],
  overlay_pdf_text: [
    "pdf",
    "form",
    "write on pdf",
    "complete form",
    "fill in",
    "annotate pdf",
    "scanned form",
    "non-fillable",
    "tick box",
    "checkbox",
    "stamp text",
  ],
  // Nobody calls it "a WordprocessingML package". They call it the Word file,
  // the doc, the questionnaire someone sent — and they ask about the thing
  // they want done to it, not about the format.
  read_docx: [
    "docx",
    "word",
    "word document",
    "doc",
    "read a document",
    "questionnaire",
    "open the attachment",
  ],
  edit_docx: [
    "docx",
    "word",
    "word document",
    "edit a document",
    "fill in",
    "complete form",
    "questionnaire",
    "answer the questions",
    "find and replace",
    "redline",
  ],
  convert_to_pdf: [
    "convert to pdf",
    "word to pdf",
    "docx to pdf",
    "save as pdf",
    "export as pdf",
    "turn into a pdf",
    "make it a pdf",
    "pdf version",
  ],
  create_docx: [
    "docx",
    "word",
    "word document",
    "write a document",
    "write a report",
    "memo",
    "proposal",
    "letter",
    "export to word",
  ],

  // Web — people ask to "look something up", not to "search the web".
  search_web: ["google", "look up", "search online", "find online", "internet"],
  fetch_web_page: ["open url", "read page", "website", "link", "browse"],
  download_web_file: [
    "download",
    "get the form",
    "blank form",
    "save the pdf",
    "find the form online",
  ],

  // Everything else where an obvious synonym is missing.
  create_routine: ["schedule", "recurring", "cron", "every day", "automate"],
  update_routine: ["schedule", "reschedule", "pause", "resume", "edit schedule"],
  delete_routine: ["schedule", "stop recurring"],
  list_routines: ["schedule", "recurring", "cron"],
  get_routine: ["schedule", "recurring", "cron", "read routine", "routine brief"],
  // A Run is asked about by its outcome, never by the word "run": nothing in
  // either description matches "did it work" or "why did it fail", and before
  // these tools existed the answer to both was that the employee could not
  // look at all.
  list_runs: ["run history", "did it work", "last run", "what happened"],
  get_run_report: ["run evidence", "why did it fail", "check results", "what did it change"],
  list_goals: ["kpi", "okr", "objective", "target", "metric", "mission"],
  get_goal: ["kpi", "okr", "objective", "target"],
  update_goal_progress: ["kpi", "okr", "report progress", "metric update", "number"],
  decide_decision: ["routed", "answer decision", "decide for", "delegated judgment"],
  schedule_wakeup: ["remind me", "check back", "later", "follow up", "tomorrow", "in two days"],
  cancel_wakeup: ["remind", "unschedule"],
  create_workstream: ["long running", "multi-day", "track progress", "state", "wip"],
  update_workstream: ["save progress", "checkpoint", "state", "where i left off"],
  list_workstreams: ["in progress", "wip", "where i left off"],
  propose_initiative: ["new routine idea", "should exist", "suggest work", "noticed a gap"],
  propose_revision: [
    "edit my soul",
    "improve skill",
    "rewrite routine",
    "self-modification",
    "change my prompt",
    "update playbook",
  ],
  create_project: ["board", "workstream"],
  create_todo: ["task", "ticket", "action item", "to-do"],
  update_todo: ["task", "ticket", "complete", "close", "done"],
  list_todos: ["task", "ticket", "action item"],
  add_journal_entry: ["log", "diary", "record what i did", "decision log"],
  list_journal: ["log", "diary", "history"],
  send_workspace_message: ["slack", "chat", "post", "channel", "message the team"],
  list_workspace_channels: ["slack", "chat", "channel"],
  create_workspace_channel: ["slack", "chat", "channel"],
  rename_workspace_channel: ["slack", "channel"],
  archive_workspace_channel: ["slack", "channel", "close channel"],
  create_handoff: ["delegate", "escalate", "hand over", "ask a colleague"],
  list_handoffs: ["delegate", "escalate", "my queue"],
  complete_handoff: ["done", "resolve"],

  // Decisions — a human choosing, not a colleague taking the work. The overlap
  // with handoff vocabulary ("escalate", "ask") is deliberate: a model reaching
  // for either phrasing should see both and pick.
  request_decision: [
    "ask a human",
    "ask the team",
    "escalate to a human",
    "human in the loop",
    "sign off",
    "approve this draft",
    "which option",
    "i am stuck",
    "need a decision",
    "check with someone",
  ],
  list_decisions: ["what did they choose", "answer", "my questions", "did they reply"],
  cancel_decision: ["retract", "never mind", "withdraw question"],
  decline_handoff: ["reject", "refuse"],
  cancel_handoff: ["withdraw"],
  list_repositories: ["git", "repo", "codebase", "source"],
  // What somebody types here is the job ("fix the bug", "send me a PR"), never
  // "work session" — they do not know that is the thing standing between the
  // employee and the code.
  start_repository_work_session: [
    "repo",
    "code",
    "fix",
    "edit code",
    "change code",
    "write code",
    "pull request",
    "pr",
    "patch",
    "branch",
    "implement",
    "refactor",
    "work session",
  ],
  repository_list_files: ["repo", "files", "tree", "browse", "directory"],
  repository_read_file: ["repo", "file", "read", "open", "source"],
  repository_write_file: ["repo", "file", "write", "create", "save"],
  repository_edit_file: ["repo", "file", "edit", "replace", "change", "patch"],
  repository_delete_file: ["repo", "file", "delete", "remove"],
  repository_search: ["repo", "search", "grep", "find", "mentions", "regex"],
  repository_glob: ["repo", "glob", "find files", "pattern", "which files"],
  repository_status: ["repo", "status", "git status", "uncommitted", "changed files"],
  repository_diff: ["repo", "diff", "git diff", "review changes", "what changed"],
  repository_update_steps: ["repo", "plan", "steps", "todo", "checklist", "progress"],
  repository_run_command: [
    "repo",
    "run",
    "command",
    "shell",
    "bash",
    "terminal",
    "test",
    "tests",
    "lint",
    "build",
    "compile",
    "typecheck",
    "check my work",
  ],
  repository_commit: ["repo", "commit", "git", "save", "record"],
  list_employees: ["team", "colleague", "who else", "roster"],
  list_teams: ["team", "department", "group"],
  list_pipelines: [
    "automation",
    "automations",
    "workflow",
    "flow",
    "n8n",
    "zapier",
    "what automations do we have",
  ],
  get_pipeline: ["automation", "workflow", "flow", "webhook url", "inspect an automation"],
  list_pipeline_node_types: [
    "step library",
    "what steps can a pipeline do",
    "node types",
    "automation building blocks",
    "trigger types",
  ],
  create_pipeline: [
    "automate this",
    "build an automation",
    "workflow",
    "receiver",
    "webhook endpoint",
    "webhook receiver",
    "accept a webhook",
    "no-code automation",
    "zapier",
    "n8n",
    "wire this up",
  ],
  update_pipeline: [
    "edit an automation",
    "change a workflow",
    "pause an automation",
    "disable automation",
  ],
  delete_pipeline: ["remove an automation", "delete a workflow"],
  run_pipeline: ["run now", "test an automation", "fire a workflow", "trigger manually"],
  list_pipeline_runs: [
    "automation history",
    "did the webhook arrive",
    "is the automation working",
    "workflow runs",
  ],
  get_pipeline_run: ["why did the automation fail", "automation log", "workflow error"],
  rotate_pipeline_webhook_token: [
    "rotate webhook secret",
    "new webhook url",
    "webhook leaked",
    "regenerate token",
  ],
  get_self: ["who am i", "my role", "myself"],
  list_skills: ["playbook", "procedure", "sop"],
  create_skill: ["playbook", "procedure", "sop", "write a playbook"],
  update_skill: ["playbook", "procedure", "sop"],
  delete_skill: ["playbook", "procedure"],
  add_memory: ["remember", "note to self", "durable fact"],
  list_memory: ["remember", "what do i know"],
  update_memory: ["remember", "correct a fact"],
  delete_memory: ["forget"],
};

/** Domain key for a manifest tool name, or undefined if it has no home. */
export function domainOf(toolName: string): string | undefined {
  for (const [key, domain] of Object.entries(TOOL_DOMAINS)) {
    if (domain.tools.includes(toolName)) return key;
  }
  return undefined;
}

/**
 * Fail at boot if the index and the manifest have drifted apart.
 *
 * Copies the idiom `collapseStaticTools()` already uses: a tool that exists but
 * sits in no domain is invisible to `find_tools`, which is the one failure mode
 * this whole design cannot tolerate — the capability is present, reachable, and
 * undiscoverable. Better to refuse to start than to ship a hole.
 */
export function assertIndexCoversManifest(): void {
  const indexed = new Set(Object.values(TOOL_DOMAINS).flatMap((d) => d.tools));
  const manifest = new Set(STATIC_TOOLS.map((t) => t.name));

  const missing = [...manifest].filter((n) => !indexed.has(n));
  if (missing.length > 0) {
    throw new Error(
      `TOOL_DOMAINS in toolIndex.ts does not cover ${missing.length} manifest tool(s): ` +
        `${missing.join(", ")}. Add each to a domain — an unindexed tool cannot be found ` +
        `by find_tools, so the employee has it but can never reach it.`,
    );
  }

  const stale = [...indexed].filter((n) => !manifest.has(n));
  if (stale.length > 0) {
    throw new Error(
      `TOOL_DOMAINS in toolIndex.ts names ${stale.length} tool(s) that are not in ` +
        `STATIC_TOOLS: ${stale.join(", ")}. Remove them or fix the rename.`,
    );
  }

  const badKeyword = Object.keys(TOOL_KEYWORDS).filter((n) => !manifest.has(n));
  if (badKeyword.length > 0) {
    throw new Error(
      `TOOL_KEYWORDS in toolIndex.ts names ${badKeyword.length} tool(s) that are not in ` +
        `STATIC_TOOLS: ${badKeyword.join(", ")}.`,
    );
  }
}

assertIndexCoversManifest();
