import { MigrationInterface, QueryRunner } from "typeorm";

export class RevenueSpine1784841570822 implements MigrationInterface {
    name = 'RevenueSpine1784841570822'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "contacts" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "email" varchar NOT NULL DEFAULT (''), "phone" varchar NOT NULL DEFAULT (''), "title" varchar NOT NULL DEFAULT (''), "linkedinUrl" varchar NOT NULL DEFAULT (''), "websiteUrl" varchar NOT NULL DEFAULT (''), "customerId" varchar, "companyName" varchar NOT NULL DEFAULT (''), "lifecycleStage" varchar NOT NULL DEFAULT ('lead'), "ownerId" varchar, "ownerEmployeeId" varchar, "source" varchar NOT NULL DEFAULT (''), "sourceDetail" varchar NOT NULL DEFAULT (''), "score" integer NOT NULL DEFAULT (0), "enrichedJson" text, "notes" text NOT NULL DEFAULT (''), "doNotContact" boolean NOT NULL DEFAULT (0), "unsubscribedAt" datetime, "bouncedAt" datetime, "lastActivityAt" datetime, "archivedAt" datetime, "createdById" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_c45581301c84a8b96f4f5174cc" ON "contacts" ("companyId", "lastActivityAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d321a5c3695ceb8ee8f5655988" ON "contacts" ("companyId", "archivedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4c488d49a53802623d18884fd" ON "contacts" ("companyId", "lifecycleStage") `);
        await queryRunner.query(`CREATE INDEX "IDX_38d8fa59e9edbde3bd66eb3d77" ON "contacts" ("companyId", "customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fff8748b888856f6c7625cc11b" ON "contacts" ("companyId", "email") `);
        await queryRunner.query(`CREATE TABLE "deal_stages" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "sortOrder" integer NOT NULL DEFAULT (0), "probability" integer NOT NULL DEFAULT (0), "kind" varchar NOT NULL DEFAULT ('open'), "color" varchar NOT NULL DEFAULT (''), "description" text NOT NULL DEFAULT (''), "archivedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_798eb7ffe0257287aee4db7770" ON "deal_stages" ("companyId", "archivedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f0ac964a423c9d8563ccfb148" ON "deal_stages" ("companyId", "sortOrder") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6096ae381257efae65adeca4e6" ON "deal_stages" ("companyId", "slug") `);
        await queryRunner.query(`CREATE TABLE "deals" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "title" varchar NOT NULL, "description" text NOT NULL DEFAULT (''), "customerId" varchar, "primaryContactId" varchar, "stageId" varchar NOT NULL, "amountCents" integer NOT NULL DEFAULT (0), "currency" varchar NOT NULL DEFAULT ('USD'), "probabilityOverride" integer, "expectedCloseDate" datetime, "status" varchar NOT NULL DEFAULT ('open'), "closedAt" datetime, "lostReason" varchar NOT NULL DEFAULT (''), "source" varchar NOT NULL DEFAULT (''), "ownerId" varchar, "ownerEmployeeId" varchar, "nextStep" varchar NOT NULL DEFAULT (''), "lastActivityAt" datetime, "archivedAt" datetime, "createdById" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_837b88803d23a79b88ebd9bd2c" ON "deals" ("companyId", "expectedCloseDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_98de6ef1bebb17bb0b74cef931" ON "deals" ("companyId", "closedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_feb688fb4f152b0ca1228e449e" ON "deals" ("companyId", "archivedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c419cf497b3eac82f1b6d653c7" ON "deals" ("companyId", "ownerEmployeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_251df647cb9cc143e2488db3a1" ON "deals" ("companyId", "primaryContactId") `);
        await queryRunner.query(`CREATE INDEX "IDX_be8282d6fa0ac87f2eb85b5d90" ON "deals" ("companyId", "customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_67282fe42388eefa1de17cb7de" ON "deals" ("companyId", "stageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_43ebfc877f6a4a18a232f6d7c9" ON "deals" ("companyId", "status") `);
        await queryRunner.query(`CREATE TABLE "deal_contacts" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "dealId" varchar NOT NULL, "contactId" varchar NOT NULL, "role" varchar NOT NULL DEFAULT (''), "sortOrder" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0a808d4f61d0b204f3554367e4" ON "deal_contacts" ("dealId", "contactId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d09133ea83c39ca3ef9658df69" ON "deal_contacts" ("contactId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3991be6470f78d56144b155bb5" ON "deal_contacts" ("dealId") `);
        await queryRunner.query(`CREATE TABLE "activities" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "kind" varchar NOT NULL, "subject" varchar NOT NULL DEFAULT (''), "bodyText" text NOT NULL DEFAULT (''), "occurredAt" datetime NOT NULL, "contactId" varchar, "dealId" varchar, "customerId" varchar, "mailThreadId" varchar, "mailMessageId" varchar, "actorUserId" varchar, "actorEmployeeId" varchar, "metaJson" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_47d9a8dbb573521810a5b2c3dc" ON "activities" ("companyId", "mailMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2bddf29f25d4a1752ea6eadc63" ON "activities" ("customerId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0475b6d437b908dac4a4e768b5" ON "activities" ("dealId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_823726e0acc9be30241813fbf7" ON "activities" ("contactId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5383feac2144f5b54f1ff44094" ON "activities" ("companyId", "kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_94aa9cdb289d03202f0bf2bfef" ON "activities" ("companyId", "occurredAt") `);
        await queryRunner.query(`CREATE TABLE "suppressions" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "email" varchar NOT NULL, "reason" varchar NOT NULL DEFAULT ('manual'), "source" varchar NOT NULL DEFAULT (''), "contactId" varchar, "notes" text NOT NULL DEFAULT (''), "createdById" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_695cc5425122f2325b39544a7d" ON "suppressions" ("companyId", "reason") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2908e938bf40936ef6d3954470" ON "suppressions" ("companyId", "email") `);
        await queryRunner.query(`CREATE TABLE "sequences" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "description" text NOT NULL DEFAULT (''), "status" varchar NOT NULL DEFAULT ('draft'), "mailAccountId" varchar NOT NULL, "employeeId" varchar NOT NULL, "brief" text NOT NULL DEFAULT (''), "autoSend" boolean NOT NULL DEFAULT (0), "stopOnReply" boolean NOT NULL DEFAULT (1), "dailyCap" integer NOT NULL DEFAULT (50), "sendWindowJson" text, "archivedAt" datetime, "createdById" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_5218dd1caf9a9b1ed3b5ebaac5" ON "sequences" ("companyId", "employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b158cdd1c39ffeb75863e7e2ba" ON "sequences" ("companyId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0ada014ecbfc9ad7a0ef465821" ON "sequences" ("companyId", "slug") `);
        await queryRunner.query(`CREATE TABLE "sequence_steps" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "sequenceId" varchar NOT NULL, "sortOrder" integer NOT NULL DEFAULT (0), "name" varchar NOT NULL DEFAULT (''), "delayDays" integer NOT NULL DEFAULT (3), "delayHours" integer NOT NULL DEFAULT (0), "instruction" text NOT NULL DEFAULT (''), "threadWithPrevious" boolean NOT NULL DEFAULT (1))`);
        await queryRunner.query(`CREATE INDEX "IDX_eb66c610eb3d96f66c35fa15a0" ON "sequence_steps" ("sequenceId", "sortOrder") `);
        await queryRunner.query(`CREATE TABLE "sequence_enrollments" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "sequenceId" varchar NOT NULL, "contactId" varchar NOT NULL, "dealId" varchar, "status" varchar NOT NULL DEFAULT ('active'), "currentStepOrder" integer NOT NULL DEFAULT (0), "nextRunAt" datetime, "lastStepAt" datetime, "stoppedReason" varchar NOT NULL DEFAULT (''), "mailThreadId" varchar, "createdById" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_b7e47715956a46c3847ce5d891" ON "sequence_enrollments" ("mailThreadId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1587e1c3f169ceb2f148c31176" ON "sequence_enrollments" ("companyId", "contactId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dbe0f6e04fd9d458c376c3a38c" ON "sequence_enrollments" ("status", "nextRunAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3a9b1a642dd42c58b5595640e" ON "sequence_enrollments" ("companyId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d1ab86f9f16d30a2d05cb07177" ON "sequence_enrollments" ("sequenceId", "contactId") `);
        await queryRunner.query(`CREATE TABLE "sequence_step_runs" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "sequenceId" varchar NOT NULL, "enrollmentId" varchar NOT NULL, "stepId" varchar NOT NULL, "stepOrder" integer NOT NULL DEFAULT (0), "status" varchar NOT NULL DEFAULT ('drafted'), "mailMessageId" varchar, "mailThreadId" varchar, "detail" text NOT NULL DEFAULT (''), "subject" varchar NOT NULL DEFAULT (''), "ranAt" datetime NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_87f64b3f848f52bf561bb5959b" ON "sequence_step_runs" ("enrollmentId", "stepId") `);
        await queryRunner.query(`CREATE INDEX "IDX_becc1908e607b73675b6e7f335" ON "sequence_step_runs" ("companyId", "ranAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d37ab4b5b9abc61a453654839" ON "sequence_step_runs" ("enrollmentId", "ranAt") `);
        await queryRunner.query(`CREATE TABLE "signals" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "description" text NOT NULL DEFAULT (''), "sourceKind" varchar NOT NULL DEFAULT ('sql'), "connectionId" varchar, "sql" text NOT NULL DEFAULT (''), "cron" varchar NOT NULL DEFAULT ('0 * * * *'), "enabled" boolean NOT NULL DEFAULT (0), "dedupeKeyColumn" varchar NOT NULL DEFAULT (''), "emailColumn" varchar NOT NULL DEFAULT (''), "domainColumn" varchar NOT NULL DEFAULT (''), "amountColumn" varchar NOT NULL DEFAULT (''), "actionKind" varchar NOT NULL DEFAULT ('activity'), "actionConfigJson" text, "employeeId" varchar, "lastRunAt" datetime, "lastError" text NOT NULL DEFAULT (''), "lastEventCount" integer NOT NULL DEFAULT (0), "archivedAt" datetime, "createdById" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfb2c9fbdf16b78c560cfeab6b" ON "signals" ("companyId", "enabled") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8404eecc9e43e246ded04c5748" ON "signals" ("companyId", "slug") `);
        await queryRunner.query(`CREATE TABLE "signal_events" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "signalId" varchar NOT NULL, "dedupeKey" varchar NOT NULL, "payloadJson" text, "contactId" varchar, "customerId" varchar, "dealId" varchar, "status" varchar NOT NULL DEFAULT ('new'), "detail" text NOT NULL DEFAULT (''), "occurredAt" datetime NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_875fc3d58f7b42b6e12b748301" ON "signal_events" ("contactId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4958c9db662c0a6cd73aa55d2b" ON "signal_events" ("companyId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6233982303bb01ce3e1abfa67c" ON "signal_events" ("companyId", "occurredAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_012902809eb8aa97a5e678ab61" ON "signal_events" ("signalId", "dedupeKey") `);
        await queryRunner.query(`CREATE TABLE "employee_revenue_grants" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "employeeId" varchar NOT NULL, "accessLevel" varchar NOT NULL DEFAULT ('read'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ee79c9a39779ad3cc3814aee44" ON "employee_revenue_grants" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_40b7d403db4ef96fa9bea5b55b" ON "employee_revenue_grants" ("companyId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_40b7d403db4ef96fa9bea5b55b"`);
        await queryRunner.query(`DROP INDEX "IDX_ee79c9a39779ad3cc3814aee44"`);
        await queryRunner.query(`DROP TABLE "employee_revenue_grants"`);
        await queryRunner.query(`DROP INDEX "IDX_012902809eb8aa97a5e678ab61"`);
        await queryRunner.query(`DROP INDEX "IDX_6233982303bb01ce3e1abfa67c"`);
        await queryRunner.query(`DROP INDEX "IDX_4958c9db662c0a6cd73aa55d2b"`);
        await queryRunner.query(`DROP INDEX "IDX_875fc3d58f7b42b6e12b748301"`);
        await queryRunner.query(`DROP TABLE "signal_events"`);
        await queryRunner.query(`DROP INDEX "IDX_8404eecc9e43e246ded04c5748"`);
        await queryRunner.query(`DROP INDEX "IDX_cfb2c9fbdf16b78c560cfeab6b"`);
        await queryRunner.query(`DROP TABLE "signals"`);
        await queryRunner.query(`DROP INDEX "IDX_9d37ab4b5b9abc61a453654839"`);
        await queryRunner.query(`DROP INDEX "IDX_becc1908e607b73675b6e7f335"`);
        await queryRunner.query(`DROP INDEX "IDX_87f64b3f848f52bf561bb5959b"`);
        await queryRunner.query(`DROP TABLE "sequence_step_runs"`);
        await queryRunner.query(`DROP INDEX "IDX_d1ab86f9f16d30a2d05cb07177"`);
        await queryRunner.query(`DROP INDEX "IDX_a3a9b1a642dd42c58b5595640e"`);
        await queryRunner.query(`DROP INDEX "IDX_dbe0f6e04fd9d458c376c3a38c"`);
        await queryRunner.query(`DROP INDEX "IDX_1587e1c3f169ceb2f148c31176"`);
        await queryRunner.query(`DROP INDEX "IDX_b7e47715956a46c3847ce5d891"`);
        await queryRunner.query(`DROP TABLE "sequence_enrollments"`);
        await queryRunner.query(`DROP INDEX "IDX_eb66c610eb3d96f66c35fa15a0"`);
        await queryRunner.query(`DROP TABLE "sequence_steps"`);
        await queryRunner.query(`DROP INDEX "IDX_0ada014ecbfc9ad7a0ef465821"`);
        await queryRunner.query(`DROP INDEX "IDX_b158cdd1c39ffeb75863e7e2ba"`);
        await queryRunner.query(`DROP INDEX "IDX_5218dd1caf9a9b1ed3b5ebaac5"`);
        await queryRunner.query(`DROP TABLE "sequences"`);
        await queryRunner.query(`DROP INDEX "IDX_2908e938bf40936ef6d3954470"`);
        await queryRunner.query(`DROP INDEX "IDX_695cc5425122f2325b39544a7d"`);
        await queryRunner.query(`DROP TABLE "suppressions"`);
        await queryRunner.query(`DROP INDEX "IDX_94aa9cdb289d03202f0bf2bfef"`);
        await queryRunner.query(`DROP INDEX "IDX_5383feac2144f5b54f1ff44094"`);
        await queryRunner.query(`DROP INDEX "IDX_823726e0acc9be30241813fbf7"`);
        await queryRunner.query(`DROP INDEX "IDX_0475b6d437b908dac4a4e768b5"`);
        await queryRunner.query(`DROP INDEX "IDX_2bddf29f25d4a1752ea6eadc63"`);
        await queryRunner.query(`DROP INDEX "IDX_47d9a8dbb573521810a5b2c3dc"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP INDEX "IDX_3991be6470f78d56144b155bb5"`);
        await queryRunner.query(`DROP INDEX "IDX_d09133ea83c39ca3ef9658df69"`);
        await queryRunner.query(`DROP INDEX "IDX_0a808d4f61d0b204f3554367e4"`);
        await queryRunner.query(`DROP TABLE "deal_contacts"`);
        await queryRunner.query(`DROP INDEX "IDX_43ebfc877f6a4a18a232f6d7c9"`);
        await queryRunner.query(`DROP INDEX "IDX_67282fe42388eefa1de17cb7de"`);
        await queryRunner.query(`DROP INDEX "IDX_be8282d6fa0ac87f2eb85b5d90"`);
        await queryRunner.query(`DROP INDEX "IDX_251df647cb9cc143e2488db3a1"`);
        await queryRunner.query(`DROP INDEX "IDX_c419cf497b3eac82f1b6d653c7"`);
        await queryRunner.query(`DROP INDEX "IDX_feb688fb4f152b0ca1228e449e"`);
        await queryRunner.query(`DROP INDEX "IDX_98de6ef1bebb17bb0b74cef931"`);
        await queryRunner.query(`DROP INDEX "IDX_837b88803d23a79b88ebd9bd2c"`);
        await queryRunner.query(`DROP TABLE "deals"`);
        await queryRunner.query(`DROP INDEX "IDX_6096ae381257efae65adeca4e6"`);
        await queryRunner.query(`DROP INDEX "IDX_8f0ac964a423c9d8563ccfb148"`);
        await queryRunner.query(`DROP INDEX "IDX_798eb7ffe0257287aee4db7770"`);
        await queryRunner.query(`DROP TABLE "deal_stages"`);
        await queryRunner.query(`DROP INDEX "IDX_fff8748b888856f6c7625cc11b"`);
        await queryRunner.query(`DROP INDEX "IDX_38d8fa59e9edbde3bd66eb3d77"`);
        await queryRunner.query(`DROP INDEX "IDX_a4c488d49a53802623d18884fd"`);
        await queryRunner.query(`DROP INDEX "IDX_d321a5c3695ceb8ee8f5655988"`);
        await queryRunner.query(`DROP INDEX "IDX_c45581301c84a8b96f4f5174cc"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
    }

}
