import { MigrationInterface, QueryRunner } from "typeorm";

export class RevenueOperations1784990767793 implements MigrationInterface {
    name = 'RevenueOperations1784990767793'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "revenue_classifications" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "kind" varchar NOT NULL, "value" varchar NOT NULL, "label" varchar NOT NULL, "sortOrder" integer NOT NULL DEFAULT (0), "archivedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_f75f797617263fa2795e9c7682" ON "revenue_classifications" ("companyId", "kind", "sortOrder") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_39f1b6dec2a9ff3628ab2e19cf" ON "revenue_classifications" ("companyId", "kind", "value") `);
        await queryRunner.query(`CREATE TABLE "revenue_custom_fields" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "resourceType" varchar NOT NULL, "key" varchar NOT NULL, "name" varchar NOT NULL, "fieldType" varchar NOT NULL, "optionsJson" text NOT NULL DEFAULT ('[]'), "required" boolean NOT NULL DEFAULT (0), "sortOrder" integer NOT NULL DEFAULT (0), "archivedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc95fa571960717afb3d4d4f0f" ON "revenue_custom_fields" ("companyId", "resourceType", "sortOrder") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b739a7faa4beeafff945731d36" ON "revenue_custom_fields" ("companyId", "resourceType", "key") `);
        await queryRunner.query(`CREATE TABLE "revenue_custom_values" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "fieldId" varchar NOT NULL, "resourceType" varchar NOT NULL, "resourceId" varchar NOT NULL, "valueJson" text NOT NULL, "searchValue" varchar NOT NULL DEFAULT (''), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_537b4e6c5aaf3b23b50d11d203" ON "revenue_custom_values" ("companyId", "fieldId", "searchValue") `);
        await queryRunner.query(`CREATE INDEX "IDX_58068e99ec39cbec78a9eed3f7" ON "revenue_custom_values" ("companyId", "resourceType", "resourceId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b4e44c6687106223c2d15ef2e5" ON "revenue_custom_values" ("companyId", "fieldId", "resourceId") `);
        await queryRunner.query(`CREATE TABLE "partnerships" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "type" varchar NOT NULL DEFAULT (''), "status" varchar NOT NULL DEFAULT (''), "customerId" varchar, "websiteUrl" varchar NOT NULL DEFAULT (''), "integrationContext" text NOT NULL DEFAULT (''), "channelContext" text NOT NULL DEFAULT (''), "notes" text NOT NULL DEFAULT (''), "ownerId" varchar, "ownerEmployeeId" varchar, "nextFollowUpAt" datetime, "reminderAt" datetime, "lastActivityAt" datetime, "archivedAt" datetime, "createdById" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_0562460e47c6567e7c4a2ecf0b" ON "partnerships" ("companyId", "archivedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6970560b5f631019855719697" ON "partnerships" ("companyId", "nextFollowUpAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_282e1dc8d8984fd3c09d42e6ac" ON "partnerships" ("companyId", "status") `);
        await queryRunner.query(`CREATE TABLE "partnership_contacts" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "partnershipId" varchar NOT NULL, "contactId" varchar NOT NULL, "role" varchar NOT NULL DEFAULT (''), "isPrimary" boolean NOT NULL DEFAULT (0), "replyAll" boolean NOT NULL DEFAULT (0), "sortOrder" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_53bcea13c4502e080017523dac" ON "partnership_contacts" ("companyId", "contactId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d9cc826ae147d56000d10add1b" ON "partnership_contacts" ("companyId", "partnershipId", "contactId") `);
        await queryRunner.query(`CREATE TABLE "revenue_documents" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "kind" varchar NOT NULL, "title" varchar NOT NULL, "notes" text NOT NULL DEFAULT (''), "dealId" varchar, "customerId" varchar, "partnershipId" varchar, "contactId" varchar, "attachmentId" varchar, "sourceMailMessageId" varchar, "externalUrl" varchar NOT NULL DEFAULT (''), "createdByUserId" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_725f4c1a7d34b794290b0ac08b" ON "revenue_documents" ("companyId", "contactId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6e1e6843d68df6880c73fdb8b" ON "revenue_documents" ("companyId", "partnershipId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ecbf03e13486b18a729e2f392" ON "revenue_documents" ("companyId", "customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e2f3e906b858cae25a64c27ce" ON "revenue_documents" ("companyId", "dealId") `);
        await queryRunner.query(`CREATE TABLE "revenue_import_batches" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "resourceType" varchar NOT NULL, "sourceKind" varchar NOT NULL, "sourceLabel" varchar NOT NULL DEFAULT (''), "sourceBaseId" varchar, "sourceTableId" varchar, "status" varchar NOT NULL, "mappingJson" text NOT NULL, "rowMapJson" text NOT NULL, "createdIdsJson" text NOT NULL, "reportJson" text NOT NULL, "rolledBackAt" datetime, "createdByUserId" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7cf5cf8c67bbbb8c9acb93eea" ON "revenue_import_batches" ("companyId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3b13b6afcb0e35e93da44cbf3" ON "revenue_import_batches" ("companyId", "createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_8bc655492a3f2878a887a75b86"`);
        await queryRunner.query(`DROP INDEX "IDX_e8ba264e557c27ffe461eb6c69"`);
        await queryRunner.query(`CREATE TABLE "temporary_customers" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "email" varchar NOT NULL DEFAULT (''), "phone" varchar NOT NULL DEFAULT (''), "billingAddress" text NOT NULL DEFAULT (''), "shippingAddress" text NOT NULL DEFAULT (''), "taxNumber" varchar NOT NULL DEFAULT (''), "currency" varchar NOT NULL DEFAULT ('USD'), "notes" text NOT NULL DEFAULT (''), "archivedAt" datetime, "createdById" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "annualContractValueCents" integer NOT NULL DEFAULT (0), "accountStatus" varchar NOT NULL DEFAULT ('customer'), "domain" varchar NOT NULL DEFAULT (''), "websiteUrl" varchar NOT NULL DEFAULT (''), "industry" varchar NOT NULL DEFAULT (''), "employeeCount" integer NOT NULL DEFAULT (0), "ownerId" varchar, "ownerEmployeeId" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_customers"("id", "companyId", "name", "slug", "email", "phone", "billingAddress", "shippingAddress", "taxNumber", "currency", "notes", "archivedAt", "createdById", "createdAt", "updatedAt", "annualContractValueCents") SELECT "id", "companyId", "name", "slug", "email", "phone", "billingAddress", "shippingAddress", "taxNumber", "currency", "notes", "archivedAt", "createdById", "createdAt", "updatedAt", "annualContractValueCents" FROM "customers"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`ALTER TABLE "temporary_customers" RENAME TO "customers"`);
        await queryRunner.query(`CREATE INDEX "IDX_8bc655492a3f2878a887a75b86" ON "customers" ("companyId", "archivedAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e8ba264e557c27ffe461eb6c69" ON "customers" ("companyId", "slug") `);
        await queryRunner.query(`DROP INDEX "IDX_43ebfc877f6a4a18a232f6d7c9"`);
        await queryRunner.query(`DROP INDEX "IDX_67282fe42388eefa1de17cb7de"`);
        await queryRunner.query(`DROP INDEX "IDX_be8282d6fa0ac87f2eb85b5d90"`);
        await queryRunner.query(`DROP INDEX "IDX_251df647cb9cc143e2488db3a1"`);
        await queryRunner.query(`DROP INDEX "IDX_c419cf497b3eac82f1b6d653c7"`);
        await queryRunner.query(`DROP INDEX "IDX_feb688fb4f152b0ca1228e449e"`);
        await queryRunner.query(`DROP INDEX "IDX_98de6ef1bebb17bb0b74cef931"`);
        await queryRunner.query(`DROP INDEX "IDX_837b88803d23a79b88ebd9bd2c"`);
        await queryRunner.query(`CREATE TABLE "temporary_deals" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "title" varchar NOT NULL, "description" text NOT NULL DEFAULT (''), "customerId" varchar, "primaryContactId" varchar, "stageId" varchar NOT NULL, "amountCents" integer NOT NULL DEFAULT (0), "currency" varchar NOT NULL DEFAULT ('USD'), "probabilityOverride" integer, "expectedCloseDate" datetime, "status" varchar NOT NULL DEFAULT ('open'), "closedAt" datetime, "lostReason" varchar NOT NULL DEFAULT (''), "source" varchar NOT NULL DEFAULT (''), "ownerId" varchar, "ownerEmployeeId" varchar, "nextStep" varchar NOT NULL DEFAULT (''), "lastActivityAt" datetime, "archivedAt" datetime, "createdById" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "nextFollowUpAt" datetime, "followUpReminderAt" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_deals"("id", "companyId", "title", "description", "customerId", "primaryContactId", "stageId", "amountCents", "currency", "probabilityOverride", "expectedCloseDate", "status", "closedAt", "lostReason", "source", "ownerId", "ownerEmployeeId", "nextStep", "lastActivityAt", "archivedAt", "createdById", "createdByEmployeeId", "createdAt", "updatedAt") SELECT "id", "companyId", "title", "description", "customerId", "primaryContactId", "stageId", "amountCents", "currency", "probabilityOverride", "expectedCloseDate", "status", "closedAt", "lostReason", "source", "ownerId", "ownerEmployeeId", "nextStep", "lastActivityAt", "archivedAt", "createdById", "createdByEmployeeId", "createdAt", "updatedAt" FROM "deals"`);
        await queryRunner.query(`DROP TABLE "deals"`);
        await queryRunner.query(`ALTER TABLE "temporary_deals" RENAME TO "deals"`);
        await queryRunner.query(`CREATE INDEX "IDX_43ebfc877f6a4a18a232f6d7c9" ON "deals" ("companyId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_67282fe42388eefa1de17cb7de" ON "deals" ("companyId", "stageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_be8282d6fa0ac87f2eb85b5d90" ON "deals" ("companyId", "customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_251df647cb9cc143e2488db3a1" ON "deals" ("companyId", "primaryContactId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c419cf497b3eac82f1b6d653c7" ON "deals" ("companyId", "ownerEmployeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_feb688fb4f152b0ca1228e449e" ON "deals" ("companyId", "archivedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_98de6ef1bebb17bb0b74cef931" ON "deals" ("companyId", "closedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_837b88803d23a79b88ebd9bd2c" ON "deals" ("companyId", "expectedCloseDate") `);
        await queryRunner.query(`DROP INDEX "IDX_94aa9cdb289d03202f0bf2bfef"`);
        await queryRunner.query(`DROP INDEX "IDX_5383feac2144f5b54f1ff44094"`);
        await queryRunner.query(`DROP INDEX "IDX_823726e0acc9be30241813fbf7"`);
        await queryRunner.query(`DROP INDEX "IDX_0475b6d437b908dac4a4e768b5"`);
        await queryRunner.query(`DROP INDEX "IDX_2bddf29f25d4a1752ea6eadc63"`);
        await queryRunner.query(`DROP INDEX "IDX_47d9a8dbb573521810a5b2c3dc"`);
        await queryRunner.query(`CREATE TABLE "temporary_activities" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "kind" varchar NOT NULL, "subject" varchar NOT NULL DEFAULT (''), "bodyText" text NOT NULL DEFAULT (''), "occurredAt" datetime NOT NULL, "contactId" varchar, "dealId" varchar, "customerId" varchar, "mailThreadId" varchar, "mailMessageId" varchar, "actorUserId" varchar, "actorEmployeeId" varchar, "metaJson" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "partnershipId" varchar, "taskStatus" varchar, "dueAt" datetime, "completedAt" datetime, "assignedUserId" varchar, "assignedEmployeeId" varchar, "priority" varchar, "reminderAt" datetime, "recurrenceRule" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_activities"("id", "companyId", "kind", "subject", "bodyText", "occurredAt", "contactId", "dealId", "customerId", "mailThreadId", "mailMessageId", "actorUserId", "actorEmployeeId", "metaJson", "createdAt") SELECT "id", "companyId", "kind", "subject", "bodyText", "occurredAt", "contactId", "dealId", "customerId", "mailThreadId", "mailMessageId", "actorUserId", "actorEmployeeId", "metaJson", "createdAt" FROM "activities"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`ALTER TABLE "temporary_activities" RENAME TO "activities"`);
        await queryRunner.query(`CREATE INDEX "IDX_94aa9cdb289d03202f0bf2bfef" ON "activities" ("companyId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5383feac2144f5b54f1ff44094" ON "activities" ("companyId", "kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_823726e0acc9be30241813fbf7" ON "activities" ("contactId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0475b6d437b908dac4a4e768b5" ON "activities" ("dealId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2bddf29f25d4a1752ea6eadc63" ON "activities" ("customerId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_47d9a8dbb573521810a5b2c3dc" ON "activities" ("companyId", "mailMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_34d1051b5ebae7aaeb9c54ad52" ON "customers" ("companyId", "domain") `);
        await queryRunner.query(`CREATE INDEX "IDX_957b8dd8c17aac17229369e91c" ON "customers" ("companyId", "accountStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_066afacb0091745b417e9173cf" ON "deals" ("companyId", "nextFollowUpAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c89d0d47933afc5511e84a9e56" ON "activities" ("companyId", "taskStatus", "dueAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_dcfba5f8376b0161f592f0530a" ON "activities" ("partnershipId", "occurredAt") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_dcfba5f8376b0161f592f0530a"`);
        await queryRunner.query(`DROP INDEX "IDX_c89d0d47933afc5511e84a9e56"`);
        await queryRunner.query(`DROP INDEX "IDX_066afacb0091745b417e9173cf"`);
        await queryRunner.query(`DROP INDEX "IDX_957b8dd8c17aac17229369e91c"`);
        await queryRunner.query(`DROP INDEX "IDX_34d1051b5ebae7aaeb9c54ad52"`);
        await queryRunner.query(`DROP INDEX "IDX_47d9a8dbb573521810a5b2c3dc"`);
        await queryRunner.query(`DROP INDEX "IDX_2bddf29f25d4a1752ea6eadc63"`);
        await queryRunner.query(`DROP INDEX "IDX_0475b6d437b908dac4a4e768b5"`);
        await queryRunner.query(`DROP INDEX "IDX_823726e0acc9be30241813fbf7"`);
        await queryRunner.query(`DROP INDEX "IDX_5383feac2144f5b54f1ff44094"`);
        await queryRunner.query(`DROP INDEX "IDX_94aa9cdb289d03202f0bf2bfef"`);
        await queryRunner.query(`ALTER TABLE "activities" RENAME TO "temporary_activities"`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "kind" varchar NOT NULL, "subject" varchar NOT NULL DEFAULT (''), "bodyText" text NOT NULL DEFAULT (''), "occurredAt" datetime NOT NULL, "contactId" varchar, "dealId" varchar, "customerId" varchar, "mailThreadId" varchar, "mailMessageId" varchar, "actorUserId" varchar, "actorEmployeeId" varchar, "metaJson" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "activities"("id", "companyId", "kind", "subject", "bodyText", "occurredAt", "contactId", "dealId", "customerId", "mailThreadId", "mailMessageId", "actorUserId", "actorEmployeeId", "metaJson", "createdAt") SELECT "id", "companyId", "kind", "subject", "bodyText", "occurredAt", "contactId", "dealId", "customerId", "mailThreadId", "mailMessageId", "actorUserId", "actorEmployeeId", "metaJson", "createdAt" FROM "temporary_activities"`);
        await queryRunner.query(`DROP TABLE "temporary_activities"`);
        await queryRunner.query(`CREATE INDEX "IDX_47d9a8dbb573521810a5b2c3dc" ON "activities" ("companyId", "mailMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2bddf29f25d4a1752ea6eadc63" ON "activities" ("customerId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0475b6d437b908dac4a4e768b5" ON "activities" ("dealId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_823726e0acc9be30241813fbf7" ON "activities" ("contactId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5383feac2144f5b54f1ff44094" ON "activities" ("companyId", "kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_94aa9cdb289d03202f0bf2bfef" ON "activities" ("companyId", "occurredAt") `);
        await queryRunner.query(`DROP INDEX "IDX_837b88803d23a79b88ebd9bd2c"`);
        await queryRunner.query(`DROP INDEX "IDX_98de6ef1bebb17bb0b74cef931"`);
        await queryRunner.query(`DROP INDEX "IDX_feb688fb4f152b0ca1228e449e"`);
        await queryRunner.query(`DROP INDEX "IDX_c419cf497b3eac82f1b6d653c7"`);
        await queryRunner.query(`DROP INDEX "IDX_251df647cb9cc143e2488db3a1"`);
        await queryRunner.query(`DROP INDEX "IDX_be8282d6fa0ac87f2eb85b5d90"`);
        await queryRunner.query(`DROP INDEX "IDX_67282fe42388eefa1de17cb7de"`);
        await queryRunner.query(`DROP INDEX "IDX_43ebfc877f6a4a18a232f6d7c9"`);
        await queryRunner.query(`ALTER TABLE "deals" RENAME TO "temporary_deals"`);
        await queryRunner.query(`CREATE TABLE "deals" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "title" varchar NOT NULL, "description" text NOT NULL DEFAULT (''), "customerId" varchar, "primaryContactId" varchar, "stageId" varchar NOT NULL, "amountCents" integer NOT NULL DEFAULT (0), "currency" varchar NOT NULL DEFAULT ('USD'), "probabilityOverride" integer, "expectedCloseDate" datetime, "status" varchar NOT NULL DEFAULT ('open'), "closedAt" datetime, "lostReason" varchar NOT NULL DEFAULT (''), "source" varchar NOT NULL DEFAULT (''), "ownerId" varchar, "ownerEmployeeId" varchar, "nextStep" varchar NOT NULL DEFAULT (''), "lastActivityAt" datetime, "archivedAt" datetime, "createdById" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "deals"("id", "companyId", "title", "description", "customerId", "primaryContactId", "stageId", "amountCents", "currency", "probabilityOverride", "expectedCloseDate", "status", "closedAt", "lostReason", "source", "ownerId", "ownerEmployeeId", "nextStep", "lastActivityAt", "archivedAt", "createdById", "createdByEmployeeId", "createdAt", "updatedAt") SELECT "id", "companyId", "title", "description", "customerId", "primaryContactId", "stageId", "amountCents", "currency", "probabilityOverride", "expectedCloseDate", "status", "closedAt", "lostReason", "source", "ownerId", "ownerEmployeeId", "nextStep", "lastActivityAt", "archivedAt", "createdById", "createdByEmployeeId", "createdAt", "updatedAt" FROM "temporary_deals"`);
        await queryRunner.query(`DROP TABLE "temporary_deals"`);
        await queryRunner.query(`CREATE INDEX "IDX_837b88803d23a79b88ebd9bd2c" ON "deals" ("companyId", "expectedCloseDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_98de6ef1bebb17bb0b74cef931" ON "deals" ("companyId", "closedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_feb688fb4f152b0ca1228e449e" ON "deals" ("companyId", "archivedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c419cf497b3eac82f1b6d653c7" ON "deals" ("companyId", "ownerEmployeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_251df647cb9cc143e2488db3a1" ON "deals" ("companyId", "primaryContactId") `);
        await queryRunner.query(`CREATE INDEX "IDX_be8282d6fa0ac87f2eb85b5d90" ON "deals" ("companyId", "customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_67282fe42388eefa1de17cb7de" ON "deals" ("companyId", "stageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_43ebfc877f6a4a18a232f6d7c9" ON "deals" ("companyId", "status") `);
        await queryRunner.query(`DROP INDEX "IDX_e8ba264e557c27ffe461eb6c69"`);
        await queryRunner.query(`DROP INDEX "IDX_8bc655492a3f2878a887a75b86"`);
        await queryRunner.query(`ALTER TABLE "customers" RENAME TO "temporary_customers"`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "email" varchar NOT NULL DEFAULT (''), "phone" varchar NOT NULL DEFAULT (''), "billingAddress" text NOT NULL DEFAULT (''), "shippingAddress" text NOT NULL DEFAULT (''), "taxNumber" varchar NOT NULL DEFAULT (''), "currency" varchar NOT NULL DEFAULT ('USD'), "notes" text NOT NULL DEFAULT (''), "archivedAt" datetime, "createdById" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "annualContractValueCents" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "customers"("id", "companyId", "name", "slug", "email", "phone", "billingAddress", "shippingAddress", "taxNumber", "currency", "notes", "archivedAt", "createdById", "createdAt", "updatedAt", "annualContractValueCents") SELECT "id", "companyId", "name", "slug", "email", "phone", "billingAddress", "shippingAddress", "taxNumber", "currency", "notes", "archivedAt", "createdById", "createdAt", "updatedAt", "annualContractValueCents" FROM "temporary_customers"`);
        await queryRunner.query(`DROP TABLE "temporary_customers"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e8ba264e557c27ffe461eb6c69" ON "customers" ("companyId", "slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bc655492a3f2878a887a75b86" ON "customers" ("companyId", "archivedAt") `);
        await queryRunner.query(`DROP INDEX "IDX_e3b13b6afcb0e35e93da44cbf3"`);
        await queryRunner.query(`DROP INDEX "IDX_a7cf5cf8c67bbbb8c9acb93eea"`);
        await queryRunner.query(`DROP TABLE "revenue_import_batches"`);
        await queryRunner.query(`DROP INDEX "IDX_8e2f3e906b858cae25a64c27ce"`);
        await queryRunner.query(`DROP INDEX "IDX_3ecbf03e13486b18a729e2f392"`);
        await queryRunner.query(`DROP INDEX "IDX_e6e1e6843d68df6880c73fdb8b"`);
        await queryRunner.query(`DROP INDEX "IDX_725f4c1a7d34b794290b0ac08b"`);
        await queryRunner.query(`DROP TABLE "revenue_documents"`);
        await queryRunner.query(`DROP INDEX "IDX_d9cc826ae147d56000d10add1b"`);
        await queryRunner.query(`DROP INDEX "IDX_53bcea13c4502e080017523dac"`);
        await queryRunner.query(`DROP TABLE "partnership_contacts"`);
        await queryRunner.query(`DROP INDEX "IDX_282e1dc8d8984fd3c09d42e6ac"`);
        await queryRunner.query(`DROP INDEX "IDX_c6970560b5f631019855719697"`);
        await queryRunner.query(`DROP INDEX "IDX_0562460e47c6567e7c4a2ecf0b"`);
        await queryRunner.query(`DROP TABLE "partnerships"`);
        await queryRunner.query(`DROP INDEX "IDX_b4e44c6687106223c2d15ef2e5"`);
        await queryRunner.query(`DROP INDEX "IDX_58068e99ec39cbec78a9eed3f7"`);
        await queryRunner.query(`DROP INDEX "IDX_537b4e6c5aaf3b23b50d11d203"`);
        await queryRunner.query(`DROP TABLE "revenue_custom_values"`);
        await queryRunner.query(`DROP INDEX "IDX_b739a7faa4beeafff945731d36"`);
        await queryRunner.query(`DROP INDEX "IDX_dc95fa571960717afb3d4d4f0f"`);
        await queryRunner.query(`DROP TABLE "revenue_custom_fields"`);
        await queryRunner.query(`DROP INDEX "IDX_39f1b6dec2a9ff3628ab2e19cf"`);
        await queryRunner.query(`DROP INDEX "IDX_f75f797617263fa2795e9c7682"`);
        await queryRunner.query(`DROP TABLE "revenue_classifications"`);
    }

}
