import { MigrationInterface, QueryRunner } from "typeorm";

export class MarketingDecisionLayer1787125740510 implements MigrationInterface {
    name = 'MarketingDecisionLayer1787125740510'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_86573e6c78285e31926428349d"`);
        await queryRunner.query(`DROP INDEX "IDX_4d9c9c053bb724e645a5b34f58"`);
        await queryRunner.query(`DROP INDEX "IDX_75ca47bbb4d25852ddea815431"`);
        await queryRunner.query(`CREATE TABLE "temporary_marketing_campaigns" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "objective" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('draft'), "autonomyMode" varchar NOT NULL DEFAULT ('observe'), "channel" varchar NOT NULL DEFAULT (''), "connectionId" varchar, "externalAccountId" varchar NOT NULL DEFAULT (''), "externalCampaignId" varchar NOT NULL DEFAULT (''), "ownerEmployeeId" varchar, "brief" text NOT NULL DEFAULT (''), "audience" text NOT NULL DEFAULT (''), "offer" text NOT NULL DEFAULT (''), "landingPageUrl" varchar NOT NULL DEFAULT (''), "successMetric" varchar NOT NULL DEFAULT ('conversions'), "targetValue" varchar NOT NULL DEFAULT (''), "dailyBudgetMinor" integer NOT NULL DEFAULT (0), "currency" varchar NOT NULL DEFAULT ('USD'), "startsAt" datetime, "endsAt" datetime, "createdByUserId" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "targetDirection" varchar NOT NULL DEFAULT ('at_most'))`);
        await queryRunner.query(`INSERT INTO "temporary_marketing_campaigns"("id", "companyId", "name", "objective", "status", "autonomyMode", "channel", "connectionId", "externalAccountId", "externalCampaignId", "ownerEmployeeId", "brief", "audience", "offer", "landingPageUrl", "successMetric", "targetValue", "dailyBudgetMinor", "currency", "startsAt", "endsAt", "createdByUserId", "createdByEmployeeId", "createdAt", "updatedAt") SELECT "id", "companyId", "name", "objective", "status", "autonomyMode", "channel", "connectionId", "externalAccountId", "externalCampaignId", "ownerEmployeeId", "brief", "audience", "offer", "landingPageUrl", "successMetric", "targetValue", "dailyBudgetMinor", "currency", "startsAt", "endsAt", "createdByUserId", "createdByEmployeeId", "createdAt", "updatedAt" FROM "marketing_campaigns"`);
        await queryRunner.query(`DROP TABLE "marketing_campaigns"`);
        await queryRunner.query(`ALTER TABLE "temporary_marketing_campaigns" RENAME TO "marketing_campaigns"`);
        await queryRunner.query(`CREATE INDEX "IDX_86573e6c78285e31926428349d" ON "marketing_campaigns" ("companyId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d9c9c053bb724e645a5b34f58" ON "marketing_campaigns" ("companyId", "ownerEmployeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_75ca47bbb4d25852ddea815431" ON "marketing_campaigns" ("companyId", "connectionId", "externalCampaignId") `);
        await queryRunner.query(`DROP INDEX "IDX_4217fc034801bec18f8d432ecd"`);
        await queryRunner.query(`CREATE TABLE "temporary_marketing_performance_snapshots" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "campaignId" varchar NOT NULL, "periodStart" datetime NOT NULL, "periodEnd" datetime NOT NULL, "spendMinor" integer NOT NULL DEFAULT (0), "impressions" integer NOT NULL DEFAULT (0), "clicks" integer NOT NULL DEFAULT (0), "conversions" varchar NOT NULL DEFAULT ('0'), "conversionValue" varchar NOT NULL DEFAULT ('0'), "currency" varchar NOT NULL DEFAULT ('USD'), "source" varchar NOT NULL DEFAULT (''), "rawJson" text NOT NULL DEFAULT ('{}'), "recordedByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "supersededAt" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_marketing_performance_snapshots"("id", "companyId", "campaignId", "periodStart", "periodEnd", "spendMinor", "impressions", "clicks", "conversions", "conversionValue", "currency", "source", "rawJson", "recordedByEmployeeId", "createdAt") SELECT "id", "companyId", "campaignId", "periodStart", "periodEnd", "spendMinor", "impressions", "clicks", "conversions", "conversionValue", "currency", "source", "rawJson", "recordedByEmployeeId", "createdAt" FROM "marketing_performance_snapshots"`);
        await queryRunner.query(`DROP TABLE "marketing_performance_snapshots"`);
        await queryRunner.query(`ALTER TABLE "temporary_marketing_performance_snapshots" RENAME TO "marketing_performance_snapshots"`);
        await queryRunner.query(`CREATE INDEX "IDX_4217fc034801bec18f8d432ecd" ON "marketing_performance_snapshots" ("companyId", "campaignId", "periodEnd") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b209a90a5d36e764c5437bf97" ON "marketing_performance_snapshots" ("companyId", "campaignId", "periodStart", "periodEnd") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_5b209a90a5d36e764c5437bf97"`);
        await queryRunner.query(`DROP INDEX "IDX_4217fc034801bec18f8d432ecd"`);
        await queryRunner.query(`ALTER TABLE "marketing_performance_snapshots" RENAME TO "temporary_marketing_performance_snapshots"`);
        await queryRunner.query(`CREATE TABLE "marketing_performance_snapshots" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "campaignId" varchar NOT NULL, "periodStart" datetime NOT NULL, "periodEnd" datetime NOT NULL, "spendMinor" integer NOT NULL DEFAULT (0), "impressions" integer NOT NULL DEFAULT (0), "clicks" integer NOT NULL DEFAULT (0), "conversions" varchar NOT NULL DEFAULT ('0'), "conversionValue" varchar NOT NULL DEFAULT ('0'), "currency" varchar NOT NULL DEFAULT ('USD'), "source" varchar NOT NULL DEFAULT (''), "rawJson" text NOT NULL DEFAULT ('{}'), "recordedByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "marketing_performance_snapshots"("id", "companyId", "campaignId", "periodStart", "periodEnd", "spendMinor", "impressions", "clicks", "conversions", "conversionValue", "currency", "source", "rawJson", "recordedByEmployeeId", "createdAt") SELECT "id", "companyId", "campaignId", "periodStart", "periodEnd", "spendMinor", "impressions", "clicks", "conversions", "conversionValue", "currency", "source", "rawJson", "recordedByEmployeeId", "createdAt" FROM "temporary_marketing_performance_snapshots"`);
        await queryRunner.query(`DROP TABLE "temporary_marketing_performance_snapshots"`);
        await queryRunner.query(`CREATE INDEX "IDX_4217fc034801bec18f8d432ecd" ON "marketing_performance_snapshots" ("companyId", "campaignId", "periodEnd") `);
        await queryRunner.query(`DROP INDEX "IDX_75ca47bbb4d25852ddea815431"`);
        await queryRunner.query(`DROP INDEX "IDX_4d9c9c053bb724e645a5b34f58"`);
        await queryRunner.query(`DROP INDEX "IDX_86573e6c78285e31926428349d"`);
        await queryRunner.query(`ALTER TABLE "marketing_campaigns" RENAME TO "temporary_marketing_campaigns"`);
        await queryRunner.query(`CREATE TABLE "marketing_campaigns" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "objective" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('draft'), "autonomyMode" varchar NOT NULL DEFAULT ('observe'), "channel" varchar NOT NULL DEFAULT (''), "connectionId" varchar, "externalAccountId" varchar NOT NULL DEFAULT (''), "externalCampaignId" varchar NOT NULL DEFAULT (''), "ownerEmployeeId" varchar, "brief" text NOT NULL DEFAULT (''), "audience" text NOT NULL DEFAULT (''), "offer" text NOT NULL DEFAULT (''), "landingPageUrl" varchar NOT NULL DEFAULT (''), "successMetric" varchar NOT NULL DEFAULT ('conversions'), "targetValue" varchar NOT NULL DEFAULT (''), "dailyBudgetMinor" integer NOT NULL DEFAULT (0), "currency" varchar NOT NULL DEFAULT ('USD'), "startsAt" datetime, "endsAt" datetime, "createdByUserId" varchar, "createdByEmployeeId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "marketing_campaigns"("id", "companyId", "name", "objective", "status", "autonomyMode", "channel", "connectionId", "externalAccountId", "externalCampaignId", "ownerEmployeeId", "brief", "audience", "offer", "landingPageUrl", "successMetric", "targetValue", "dailyBudgetMinor", "currency", "startsAt", "endsAt", "createdByUserId", "createdByEmployeeId", "createdAt", "updatedAt") SELECT "id", "companyId", "name", "objective", "status", "autonomyMode", "channel", "connectionId", "externalAccountId", "externalCampaignId", "ownerEmployeeId", "brief", "audience", "offer", "landingPageUrl", "successMetric", "targetValue", "dailyBudgetMinor", "currency", "startsAt", "endsAt", "createdByUserId", "createdByEmployeeId", "createdAt", "updatedAt" FROM "temporary_marketing_campaigns"`);
        await queryRunner.query(`DROP TABLE "temporary_marketing_campaigns"`);
        await queryRunner.query(`CREATE INDEX "IDX_75ca47bbb4d25852ddea815431" ON "marketing_campaigns" ("companyId", "connectionId", "externalCampaignId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d9c9c053bb724e645a5b34f58" ON "marketing_campaigns" ("companyId", "ownerEmployeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86573e6c78285e31926428349d" ON "marketing_campaigns" ("companyId", "status") `);
    }

}
