import { MigrationInterface, QueryRunner } from "typeorm";

export class RunOutcomesAndStallEscalation1787757019088 implements MigrationInterface {
    name = 'RunOutcomesAndStallEscalation1787757019088'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_ef3c194cfdbf720e71464a3b30"`);
        await queryRunner.query(`DROP INDEX "IDX_59e11503010aeeab1de06f89a9"`);
        await queryRunner.query(`CREATE TABLE "temporary_routines" ("id" varchar PRIMARY KEY NOT NULL, "employeeId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "cronExpr" varchar NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "lastRunAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "timeoutSec" integer NOT NULL DEFAULT (3600), "requiresApproval" boolean NOT NULL DEFAULT (0), "webhookEnabled" boolean NOT NULL DEFAULT (0), "webhookToken" varchar, "body" text NOT NULL DEFAULT (''), "nextRunAt" datetime, "browserEnabledOverride" boolean, "modelId" varchar, "catchUpPolicy" varchar NOT NULL DEFAULT ('once'), "maxAttempts" integer NOT NULL DEFAULT (1), "retryBackoffSec" integer NOT NULL DEFAULT (60), "retryOnTimeout" boolean NOT NULL DEFAULT (0), "memberBrowserId" varchar, "folderId" varchar, "acceptanceCriteria" text NOT NULL DEFAULT (''))`);
        await queryRunner.query(`INSERT INTO "temporary_routines"("id", "employeeId", "name", "slug", "cronExpr", "enabled", "lastRunAt", "createdAt", "timeoutSec", "requiresApproval", "webhookEnabled", "webhookToken", "body", "nextRunAt", "browserEnabledOverride", "modelId", "catchUpPolicy", "maxAttempts", "retryBackoffSec", "retryOnTimeout", "memberBrowserId", "folderId") SELECT "id", "employeeId", "name", "slug", "cronExpr", "enabled", "lastRunAt", "createdAt", "timeoutSec", "requiresApproval", "webhookEnabled", "webhookToken", "body", "nextRunAt", "browserEnabledOverride", "modelId", "catchUpPolicy", "maxAttempts", "retryBackoffSec", "retryOnTimeout", "memberBrowserId", "folderId" FROM "routines"`);
        await queryRunner.query(`DROP TABLE "routines"`);
        await queryRunner.query(`ALTER TABLE "temporary_routines" RENAME TO "routines"`);
        await queryRunner.query(`CREATE INDEX "IDX_ef3c194cfdbf720e71464a3b30" ON "routines" ("enabled", "nextRunAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_59e11503010aeeab1de06f89a9" ON "routines" ("employeeId", "slug") `);
        await queryRunner.query(`DROP INDEX "IDX_677c13cd57721966e5838cea2d"`);
        await queryRunner.query(`DROP INDEX "IDX_7768e812e25e9ce2abd2a65e73"`);
        await queryRunner.query(`DROP INDEX "IDX_256fc3e671f60318bb6a3c26d7"`);
        await queryRunner.query(`CREATE TABLE "temporary_runs" ("id" varchar PRIMARY KEY NOT NULL, "routineId" varchar NOT NULL, "startedAt" datetime NOT NULL, "finishedAt" datetime, "status" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "exitCode" integer, "logContent" text NOT NULL DEFAULT (''), "dismissedAt" datetime, "triggerKind" varchar NOT NULL DEFAULT ('schedule'), "attempt" integer NOT NULL DEFAULT (1), "parentRunId" varchar, "retryAt" datetime, "missedSlots" integer NOT NULL DEFAULT (0), "outcomeVerdict" varchar, "outcomeNote" text, "tokensIn" integer NOT NULL DEFAULT (0), "tokensOut" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "temporary_runs"("id", "routineId", "startedAt", "finishedAt", "status", "createdAt", "exitCode", "logContent", "dismissedAt", "triggerKind", "attempt", "parentRunId", "retryAt", "missedSlots") SELECT "id", "routineId", "startedAt", "finishedAt", "status", "createdAt", "exitCode", "logContent", "dismissedAt", "triggerKind", "attempt", "parentRunId", "retryAt", "missedSlots" FROM "runs"`);
        await queryRunner.query(`DROP TABLE "runs"`);
        await queryRunner.query(`ALTER TABLE "temporary_runs" RENAME TO "runs"`);
        await queryRunner.query(`CREATE INDEX "IDX_677c13cd57721966e5838cea2d" ON "runs" ("status", "startedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7768e812e25e9ce2abd2a65e73" ON "runs" ("retryAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_256fc3e671f60318bb6a3c26d7" ON "runs" ("routineId", "startedAt") `);
        await queryRunner.query(`DROP INDEX "IDX_df804b7a6fa13c874b10903da9"`);
        await queryRunner.query(`DROP INDEX "IDX_fbbeb7fb00740df25d6e65d36b"`);
        await queryRunner.query(`CREATE TABLE "temporary_todos" ("id" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "number" integer NOT NULL, "title" varchar NOT NULL, "description" text NOT NULL DEFAULT (''), "status" varchar NOT NULL DEFAULT ('todo'), "priority" varchar NOT NULL DEFAULT ('none'), "assigneeEmployeeId" varchar, "createdById" varchar, "dueAt" datetime, "sortOrder" float NOT NULL DEFAULT (0), "completedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "recurrence" varchar NOT NULL DEFAULT ('none'), "recurrenceParentId" varchar, "assigneeUserId" varchar, "reviewerEmployeeId" varchar, "reviewerUserId" varchar, "parentTodoId" varchar, "aiReviewPasses" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "temporary_todos"("id", "projectId", "number", "title", "description", "status", "priority", "assigneeEmployeeId", "createdById", "dueAt", "sortOrder", "completedAt", "createdAt", "updatedAt", "recurrence", "recurrenceParentId", "assigneeUserId", "reviewerEmployeeId", "reviewerUserId", "parentTodoId") SELECT "id", "projectId", "number", "title", "description", "status", "priority", "assigneeEmployeeId", "createdById", "dueAt", "sortOrder", "completedAt", "createdAt", "updatedAt", "recurrence", "recurrenceParentId", "assigneeUserId", "reviewerEmployeeId", "reviewerUserId", "parentTodoId" FROM "todos"`);
        await queryRunner.query(`DROP TABLE "todos"`);
        await queryRunner.query(`ALTER TABLE "temporary_todos" RENAME TO "todos"`);
        await queryRunner.query(`CREATE INDEX "IDX_df804b7a6fa13c874b10903da9" ON "todos" ("parentTodoId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fbbeb7fb00740df25d6e65d36b" ON "todos" ("projectId", "number") `);
        await queryRunner.query(`DROP INDEX "IDX_b61cb09f5c269da403855c6080"`);
        await queryRunner.query(`DROP INDEX "IDX_cec57feb0296840aa7d264e26b"`);
        await queryRunner.query(`DROP INDEX "IDX_d571fb585e69f28df397ab416a"`);
        await queryRunner.query(`CREATE TABLE "temporary_approvals" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "routineId" varchar NOT NULL, "employeeId" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "requestedAt" datetime NOT NULL DEFAULT (datetime('now')), "decidedAt" datetime, "decidedByUserId" varchar, "kind" varchar NOT NULL DEFAULT ('routine'), "title" varchar, "summary" text, "payloadJson" text, "resultJson" text, "errorMessage" text, "stallRemindedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_approvals"("id", "companyId", "routineId", "employeeId", "status", "requestedAt", "decidedAt", "decidedByUserId", "kind", "title", "summary", "payloadJson", "resultJson", "errorMessage") SELECT "id", "companyId", "routineId", "employeeId", "status", "requestedAt", "decidedAt", "decidedByUserId", "kind", "title", "summary", "payloadJson", "resultJson", "errorMessage" FROM "approvals"`);
        await queryRunner.query(`DROP TABLE "approvals"`);
        await queryRunner.query(`ALTER TABLE "temporary_approvals" RENAME TO "approvals"`);
        await queryRunner.query(`CREATE INDEX "IDX_b61cb09f5c269da403855c6080" ON "approvals" ("routineId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cec57feb0296840aa7d264e26b" ON "approvals" ("kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_d571fb585e69f28df397ab416a" ON "approvals" ("companyId") `);
        await queryRunner.query(`DROP INDEX "IDX_f3a3267c40488e19bf80d79b33"`);
        await queryRunner.query(`DROP INDEX "IDX_d1f21802ddf797a495d484f640"`);
        await queryRunner.query(`DROP INDEX "IDX_ad199fe6f4f207d0ec75199d39"`);
        await queryRunner.query(`CREATE TABLE "temporary_decisions" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "employeeId" varchar NOT NULL, "routineId" varchar, "runId" varchar, "conversationId" varchar, "title" varchar NOT NULL, "body" text NOT NULL DEFAULT (''), "optionsJson" text NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "urgency" varchar NOT NULL DEFAULT ('normal'), "assigneeUserId" varchar, "chosenOptionId" varchar, "chosenOptionLabel" varchar, "note" text, "decidedByUserId" varchar, "decidedAt" datetime, "expiresAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "mailThreadId" varchar, "pickupStatus" varchar NOT NULL DEFAULT ('none'), "pickupSummary" text, "pickupStartedAt" datetime, "pickupFinishedAt" datetime, "stallRemindedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_decisions"("id", "companyId", "employeeId", "routineId", "runId", "conversationId", "title", "body", "optionsJson", "status", "urgency", "assigneeUserId", "chosenOptionId", "chosenOptionLabel", "note", "decidedByUserId", "decidedAt", "expiresAt", "createdAt", "mailThreadId", "pickupStatus", "pickupSummary", "pickupStartedAt", "pickupFinishedAt") SELECT "id", "companyId", "employeeId", "routineId", "runId", "conversationId", "title", "body", "optionsJson", "status", "urgency", "assigneeUserId", "chosenOptionId", "chosenOptionLabel", "note", "decidedByUserId", "decidedAt", "expiresAt", "createdAt", "mailThreadId", "pickupStatus", "pickupSummary", "pickupStartedAt", "pickupFinishedAt" FROM "decisions"`);
        await queryRunner.query(`DROP TABLE "decisions"`);
        await queryRunner.query(`ALTER TABLE "temporary_decisions" RENAME TO "decisions"`);
        await queryRunner.query(`CREATE INDEX "IDX_f3a3267c40488e19bf80d79b33" ON "decisions" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1f21802ddf797a495d484f640" ON "decisions" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad199fe6f4f207d0ec75199d39" ON "decisions" ("companyId", "status") `);
        await queryRunner.query(`DROP INDEX "IDX_06f952b4ace7ed12375335c989"`);
        await queryRunner.query(`DROP INDEX "IDX_d6ea363931bce72ed6ddc32f2d"`);
        await queryRunner.query(`DROP INDEX "IDX_9a065800a22dc064b8e9e9bc50"`);
        await queryRunner.query(`CREATE TABLE "temporary_handoffs" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "fromEmployeeId" varchar NOT NULL, "toEmployeeId" varchar NOT NULL, "title" varchar NOT NULL, "body" text NOT NULL DEFAULT (''), "status" varchar NOT NULL DEFAULT ('pending'), "resolutionNote" text, "dueAt" datetime, "completedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "stallRemindedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_handoffs"("id", "companyId", "fromEmployeeId", "toEmployeeId", "title", "body", "status", "resolutionNote", "dueAt", "completedAt", "createdAt", "updatedAt") SELECT "id", "companyId", "fromEmployeeId", "toEmployeeId", "title", "body", "status", "resolutionNote", "dueAt", "completedAt", "createdAt", "updatedAt" FROM "handoffs"`);
        await queryRunner.query(`DROP TABLE "handoffs"`);
        await queryRunner.query(`ALTER TABLE "temporary_handoffs" RENAME TO "handoffs"`);
        await queryRunner.query(`CREATE INDEX "IDX_06f952b4ace7ed12375335c989" ON "handoffs" ("companyId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6ea363931bce72ed6ddc32f2d" ON "handoffs" ("toEmployeeId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a065800a22dc064b8e9e9bc50" ON "handoffs" ("fromEmployeeId") `);
        await queryRunner.query(`DROP INDEX "IDX_ee8cf7de39f600c1d51250df21"`);
        await queryRunner.query(`CREATE TABLE "temporary_ai_employees" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "role" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "soulBody" text NOT NULL DEFAULT (''), "avatarKey" varchar, "teamId" varchar, "reportsToEmployeeId" varchar, "reportsToUserId" varchar, "browserEnabled" boolean NOT NULL DEFAULT (0), "browserAllowedHosts" text, "browserApprovalRequired" boolean NOT NULL DEFAULT (1))`);
        await queryRunner.query(`INSERT INTO "temporary_ai_employees"("id", "companyId", "name", "slug", "role", "createdAt", "soulBody", "avatarKey", "teamId", "reportsToEmployeeId", "reportsToUserId", "browserEnabled", "browserAllowedHosts", "browserApprovalRequired") SELECT "id", "companyId", "name", "slug", "role", "createdAt", "soulBody", "avatarKey", "teamId", "reportsToEmployeeId", "reportsToUserId", "browserEnabled", "browserAllowedHosts", "browserApprovalRequired" FROM "ai_employees"`);
        await queryRunner.query(`DROP TABLE "ai_employees"`);
        await queryRunner.query(`ALTER TABLE "temporary_ai_employees" RENAME TO "ai_employees"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ee8cf7de39f600c1d51250df21" ON "ai_employees" ("companyId", "slug") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_ee8cf7de39f600c1d51250df21"`);
        await queryRunner.query(`ALTER TABLE "ai_employees" RENAME TO "temporary_ai_employees"`);
        await queryRunner.query(`CREATE TABLE "ai_employees" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "role" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "soulBody" text NOT NULL DEFAULT (''), "avatarKey" varchar, "teamId" varchar, "reportsToEmployeeId" varchar, "reportsToUserId" varchar, "browserEnabled" boolean NOT NULL DEFAULT (0), "browserAllowedHosts" text, "browserApprovalRequired" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "ai_employees"("id", "companyId", "name", "slug", "role", "createdAt", "soulBody", "avatarKey", "teamId", "reportsToEmployeeId", "reportsToUserId", "browserEnabled", "browserAllowedHosts", "browserApprovalRequired") SELECT "id", "companyId", "name", "slug", "role", "createdAt", "soulBody", "avatarKey", "teamId", "reportsToEmployeeId", "reportsToUserId", "browserEnabled", "browserAllowedHosts", "browserApprovalRequired" FROM "temporary_ai_employees"`);
        await queryRunner.query(`DROP TABLE "temporary_ai_employees"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ee8cf7de39f600c1d51250df21" ON "ai_employees" ("companyId", "slug") `);
        await queryRunner.query(`DROP INDEX "IDX_9a065800a22dc064b8e9e9bc50"`);
        await queryRunner.query(`DROP INDEX "IDX_d6ea363931bce72ed6ddc32f2d"`);
        await queryRunner.query(`DROP INDEX "IDX_06f952b4ace7ed12375335c989"`);
        await queryRunner.query(`ALTER TABLE "handoffs" RENAME TO "temporary_handoffs"`);
        await queryRunner.query(`CREATE TABLE "handoffs" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "fromEmployeeId" varchar NOT NULL, "toEmployeeId" varchar NOT NULL, "title" varchar NOT NULL, "body" text NOT NULL DEFAULT (''), "status" varchar NOT NULL DEFAULT ('pending'), "resolutionNote" text, "dueAt" datetime, "completedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "handoffs"("id", "companyId", "fromEmployeeId", "toEmployeeId", "title", "body", "status", "resolutionNote", "dueAt", "completedAt", "createdAt", "updatedAt") SELECT "id", "companyId", "fromEmployeeId", "toEmployeeId", "title", "body", "status", "resolutionNote", "dueAt", "completedAt", "createdAt", "updatedAt" FROM "temporary_handoffs"`);
        await queryRunner.query(`DROP TABLE "temporary_handoffs"`);
        await queryRunner.query(`CREATE INDEX "IDX_9a065800a22dc064b8e9e9bc50" ON "handoffs" ("fromEmployeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6ea363931bce72ed6ddc32f2d" ON "handoffs" ("toEmployeeId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_06f952b4ace7ed12375335c989" ON "handoffs" ("companyId", "status") `);
        await queryRunner.query(`DROP INDEX "IDX_ad199fe6f4f207d0ec75199d39"`);
        await queryRunner.query(`DROP INDEX "IDX_d1f21802ddf797a495d484f640"`);
        await queryRunner.query(`DROP INDEX "IDX_f3a3267c40488e19bf80d79b33"`);
        await queryRunner.query(`ALTER TABLE "decisions" RENAME TO "temporary_decisions"`);
        await queryRunner.query(`CREATE TABLE "decisions" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "employeeId" varchar NOT NULL, "routineId" varchar, "runId" varchar, "conversationId" varchar, "title" varchar NOT NULL, "body" text NOT NULL DEFAULT (''), "optionsJson" text NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "urgency" varchar NOT NULL DEFAULT ('normal'), "assigneeUserId" varchar, "chosenOptionId" varchar, "chosenOptionLabel" varchar, "note" text, "decidedByUserId" varchar, "decidedAt" datetime, "expiresAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "mailThreadId" varchar, "pickupStatus" varchar NOT NULL DEFAULT ('none'), "pickupSummary" text, "pickupStartedAt" datetime, "pickupFinishedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "decisions"("id", "companyId", "employeeId", "routineId", "runId", "conversationId", "title", "body", "optionsJson", "status", "urgency", "assigneeUserId", "chosenOptionId", "chosenOptionLabel", "note", "decidedByUserId", "decidedAt", "expiresAt", "createdAt", "mailThreadId", "pickupStatus", "pickupSummary", "pickupStartedAt", "pickupFinishedAt") SELECT "id", "companyId", "employeeId", "routineId", "runId", "conversationId", "title", "body", "optionsJson", "status", "urgency", "assigneeUserId", "chosenOptionId", "chosenOptionLabel", "note", "decidedByUserId", "decidedAt", "expiresAt", "createdAt", "mailThreadId", "pickupStatus", "pickupSummary", "pickupStartedAt", "pickupFinishedAt" FROM "temporary_decisions"`);
        await queryRunner.query(`DROP TABLE "temporary_decisions"`);
        await queryRunner.query(`CREATE INDEX "IDX_ad199fe6f4f207d0ec75199d39" ON "decisions" ("companyId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1f21802ddf797a495d484f640" ON "decisions" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3a3267c40488e19bf80d79b33" ON "decisions" ("companyId") `);
        await queryRunner.query(`DROP INDEX "IDX_d571fb585e69f28df397ab416a"`);
        await queryRunner.query(`DROP INDEX "IDX_cec57feb0296840aa7d264e26b"`);
        await queryRunner.query(`DROP INDEX "IDX_b61cb09f5c269da403855c6080"`);
        await queryRunner.query(`ALTER TABLE "approvals" RENAME TO "temporary_approvals"`);
        await queryRunner.query(`CREATE TABLE "approvals" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "routineId" varchar NOT NULL, "employeeId" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('pending'), "requestedAt" datetime NOT NULL DEFAULT (datetime('now')), "decidedAt" datetime, "decidedByUserId" varchar, "kind" varchar NOT NULL DEFAULT ('routine'), "title" varchar, "summary" text, "payloadJson" text, "resultJson" text, "errorMessage" text)`);
        await queryRunner.query(`INSERT INTO "approvals"("id", "companyId", "routineId", "employeeId", "status", "requestedAt", "decidedAt", "decidedByUserId", "kind", "title", "summary", "payloadJson", "resultJson", "errorMessage") SELECT "id", "companyId", "routineId", "employeeId", "status", "requestedAt", "decidedAt", "decidedByUserId", "kind", "title", "summary", "payloadJson", "resultJson", "errorMessage" FROM "temporary_approvals"`);
        await queryRunner.query(`DROP TABLE "temporary_approvals"`);
        await queryRunner.query(`CREATE INDEX "IDX_d571fb585e69f28df397ab416a" ON "approvals" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cec57feb0296840aa7d264e26b" ON "approvals" ("kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_b61cb09f5c269da403855c6080" ON "approvals" ("routineId") `);
        await queryRunner.query(`DROP INDEX "IDX_fbbeb7fb00740df25d6e65d36b"`);
        await queryRunner.query(`DROP INDEX "IDX_df804b7a6fa13c874b10903da9"`);
        await queryRunner.query(`ALTER TABLE "todos" RENAME TO "temporary_todos"`);
        await queryRunner.query(`CREATE TABLE "todos" ("id" varchar PRIMARY KEY NOT NULL, "projectId" varchar NOT NULL, "number" integer NOT NULL, "title" varchar NOT NULL, "description" text NOT NULL DEFAULT (''), "status" varchar NOT NULL DEFAULT ('todo'), "priority" varchar NOT NULL DEFAULT ('none'), "assigneeEmployeeId" varchar, "createdById" varchar, "dueAt" datetime, "sortOrder" float NOT NULL DEFAULT (0), "completedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "recurrence" varchar NOT NULL DEFAULT ('none'), "recurrenceParentId" varchar, "assigneeUserId" varchar, "reviewerEmployeeId" varchar, "reviewerUserId" varchar, "parentTodoId" varchar)`);
        await queryRunner.query(`INSERT INTO "todos"("id", "projectId", "number", "title", "description", "status", "priority", "assigneeEmployeeId", "createdById", "dueAt", "sortOrder", "completedAt", "createdAt", "updatedAt", "recurrence", "recurrenceParentId", "assigneeUserId", "reviewerEmployeeId", "reviewerUserId", "parentTodoId") SELECT "id", "projectId", "number", "title", "description", "status", "priority", "assigneeEmployeeId", "createdById", "dueAt", "sortOrder", "completedAt", "createdAt", "updatedAt", "recurrence", "recurrenceParentId", "assigneeUserId", "reviewerEmployeeId", "reviewerUserId", "parentTodoId" FROM "temporary_todos"`);
        await queryRunner.query(`DROP TABLE "temporary_todos"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fbbeb7fb00740df25d6e65d36b" ON "todos" ("projectId", "number") `);
        await queryRunner.query(`CREATE INDEX "IDX_df804b7a6fa13c874b10903da9" ON "todos" ("parentTodoId") `);
        await queryRunner.query(`DROP INDEX "IDX_256fc3e671f60318bb6a3c26d7"`);
        await queryRunner.query(`DROP INDEX "IDX_7768e812e25e9ce2abd2a65e73"`);
        await queryRunner.query(`DROP INDEX "IDX_677c13cd57721966e5838cea2d"`);
        await queryRunner.query(`ALTER TABLE "runs" RENAME TO "temporary_runs"`);
        await queryRunner.query(`CREATE TABLE "runs" ("id" varchar PRIMARY KEY NOT NULL, "routineId" varchar NOT NULL, "startedAt" datetime NOT NULL, "finishedAt" datetime, "status" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "exitCode" integer, "logContent" text NOT NULL DEFAULT (''), "dismissedAt" datetime, "triggerKind" varchar NOT NULL DEFAULT ('schedule'), "attempt" integer NOT NULL DEFAULT (1), "parentRunId" varchar, "retryAt" datetime, "missedSlots" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "runs"("id", "routineId", "startedAt", "finishedAt", "status", "createdAt", "exitCode", "logContent", "dismissedAt", "triggerKind", "attempt", "parentRunId", "retryAt", "missedSlots") SELECT "id", "routineId", "startedAt", "finishedAt", "status", "createdAt", "exitCode", "logContent", "dismissedAt", "triggerKind", "attempt", "parentRunId", "retryAt", "missedSlots" FROM "temporary_runs"`);
        await queryRunner.query(`DROP TABLE "temporary_runs"`);
        await queryRunner.query(`CREATE INDEX "IDX_256fc3e671f60318bb6a3c26d7" ON "runs" ("routineId", "startedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7768e812e25e9ce2abd2a65e73" ON "runs" ("retryAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_677c13cd57721966e5838cea2d" ON "runs" ("status", "startedAt") `);
        await queryRunner.query(`DROP INDEX "IDX_59e11503010aeeab1de06f89a9"`);
        await queryRunner.query(`DROP INDEX "IDX_ef3c194cfdbf720e71464a3b30"`);
        await queryRunner.query(`ALTER TABLE "routines" RENAME TO "temporary_routines"`);
        await queryRunner.query(`CREATE TABLE "routines" ("id" varchar PRIMARY KEY NOT NULL, "employeeId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "cronExpr" varchar NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "lastRunAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "timeoutSec" integer NOT NULL DEFAULT (3600), "requiresApproval" boolean NOT NULL DEFAULT (0), "webhookEnabled" boolean NOT NULL DEFAULT (0), "webhookToken" varchar, "body" text NOT NULL DEFAULT (''), "nextRunAt" datetime, "browserEnabledOverride" boolean, "modelId" varchar, "catchUpPolicy" varchar NOT NULL DEFAULT ('once'), "maxAttempts" integer NOT NULL DEFAULT (1), "retryBackoffSec" integer NOT NULL DEFAULT (60), "retryOnTimeout" boolean NOT NULL DEFAULT (0), "memberBrowserId" varchar, "folderId" varchar)`);
        await queryRunner.query(`INSERT INTO "routines"("id", "employeeId", "name", "slug", "cronExpr", "enabled", "lastRunAt", "createdAt", "timeoutSec", "requiresApproval", "webhookEnabled", "webhookToken", "body", "nextRunAt", "browserEnabledOverride", "modelId", "catchUpPolicy", "maxAttempts", "retryBackoffSec", "retryOnTimeout", "memberBrowserId", "folderId") SELECT "id", "employeeId", "name", "slug", "cronExpr", "enabled", "lastRunAt", "createdAt", "timeoutSec", "requiresApproval", "webhookEnabled", "webhookToken", "body", "nextRunAt", "browserEnabledOverride", "modelId", "catchUpPolicy", "maxAttempts", "retryBackoffSec", "retryOnTimeout", "memberBrowserId", "folderId" FROM "temporary_routines"`);
        await queryRunner.query(`DROP TABLE "temporary_routines"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_59e11503010aeeab1de06f89a9" ON "routines" ("employeeId", "slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef3c194cfdbf720e71464a3b30" ON "routines" ("enabled", "nextRunAt") `);
    }

}
