import { MigrationInterface, QueryRunner } from "typeorm";

export class MailboxProviders1788262182540 implements MigrationInterface {
    name = 'MailboxProviders1788262182540'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_e14ce68c3b10e0c7a6d5e5ef4c"`);
        await queryRunner.query(`DROP INDEX "IDX_d30a1e4d808dccb9b90ea431aa"`);
        await queryRunner.query(`CREATE TABLE "temporary_mail_accounts" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "connectionId" varchar NOT NULL, "address" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "statusMessage" varchar NOT NULL DEFAULT (''), "historyId" varchar NOT NULL DEFAULT (''), "lastSyncAt" datetime, "backfilledAt" datetime, "backfillPageToken" varchar NOT NULL DEFAULT (''), "backfilledCount" integer NOT NULL DEFAULT (0), "createdByUserId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "syncState" varchar NOT NULL DEFAULT ('idle'), "syncAttemptId" varchar, "syncStartedAt" datetime, "syncFinishedAt" datetime, "aiAnalysisEnabled" boolean NOT NULL DEFAULT (1), "aiAnalysisEmployeeId" varchar, "aiAnalysisModelId" varchar, "provider" varchar NOT NULL DEFAULT ('gmail'), "syncCursor" text NOT NULL DEFAULT (''))`);
        await queryRunner.query(`INSERT INTO "temporary_mail_accounts"("id", "companyId", "connectionId", "address", "status", "statusMessage", "historyId", "lastSyncAt", "backfilledAt", "backfillPageToken", "backfilledCount", "createdByUserId", "createdAt", "updatedAt", "syncState", "syncAttemptId", "syncStartedAt", "syncFinishedAt", "aiAnalysisEnabled", "aiAnalysisEmployeeId", "aiAnalysisModelId") SELECT "id", "companyId", "connectionId", "address", "status", "statusMessage", "historyId", "lastSyncAt", "backfilledAt", "backfillPageToken", "backfilledCount", "createdByUserId", "createdAt", "updatedAt", "syncState", "syncAttemptId", "syncStartedAt", "syncFinishedAt", "aiAnalysisEnabled", "aiAnalysisEmployeeId", "aiAnalysisModelId" FROM "mail_accounts"`);
        await queryRunner.query(`DROP TABLE "mail_accounts"`);
        await queryRunner.query(`ALTER TABLE "temporary_mail_accounts" RENAME TO "mail_accounts"`);
        await queryRunner.query(`CREATE INDEX "IDX_e14ce68c3b10e0c7a6d5e5ef4c" ON "mail_accounts" ("companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d30a1e4d808dccb9b90ea431aa" ON "mail_accounts" ("connectionId") `);
        await queryRunner.query(`DROP INDEX "IDX_9236dc41f28e0328f85094c8e4"`);
        await queryRunner.query(`DROP INDEX "IDX_2f56c2d83926c46deb50857d3f"`);
        await queryRunner.query(`DROP INDEX "IDX_9d1e1ed9661e19183e183f4828"`);
        await queryRunner.query(`CREATE TABLE "temporary_mail_messages" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "accountId" varchar NOT NULL, "threadId" varchar NOT NULL, "gmailMessageId" varchar NOT NULL, "gmailThreadId" varchar NOT NULL, "gmailDraftId" varchar NOT NULL DEFAULT (''), "fromName" varchar NOT NULL DEFAULT (''), "fromEmail" varchar NOT NULL DEFAULT (''), "toEmails" text NOT NULL DEFAULT (''), "ccEmails" text NOT NULL DEFAULT (''), "bccEmails" text NOT NULL DEFAULT (''), "subject" varchar NOT NULL DEFAULT (''), "snippet" text NOT NULL DEFAULT (''), "bodyText" text NOT NULL DEFAULT (''), "bodyHtml" text NOT NULL DEFAULT (''), "labelIds" text NOT NULL DEFAULT (''), "sentAt" datetime, "messageIdHeader" varchar NOT NULL DEFAULT (''), "referencesHeader" text NOT NULL DEFAULT (''), "inReplyToHeader" varchar NOT NULL DEFAULT (''), "attachmentsJson" text NOT NULL DEFAULT ('[]'), "sizeEstimate" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "createdByUserId" varchar, "createdByEmployeeId" varchar, "createdByRoutineId" varchar, "createdByRunId" varchar, "providerLocation" varchar NOT NULL DEFAULT (''))`);
        await queryRunner.query(`INSERT INTO "temporary_mail_messages"("id", "companyId", "accountId", "threadId", "gmailMessageId", "gmailThreadId", "gmailDraftId", "fromName", "fromEmail", "toEmails", "ccEmails", "bccEmails", "subject", "snippet", "bodyText", "bodyHtml", "labelIds", "sentAt", "messageIdHeader", "referencesHeader", "inReplyToHeader", "attachmentsJson", "sizeEstimate", "createdAt", "updatedAt", "createdByUserId", "createdByEmployeeId", "createdByRoutineId", "createdByRunId") SELECT "id", "companyId", "accountId", "threadId", "gmailMessageId", "gmailThreadId", "gmailDraftId", "fromName", "fromEmail", "toEmails", "ccEmails", "bccEmails", "subject", "snippet", "bodyText", "bodyHtml", "labelIds", "sentAt", "messageIdHeader", "referencesHeader", "inReplyToHeader", "attachmentsJson", "sizeEstimate", "createdAt", "updatedAt", "createdByUserId", "createdByEmployeeId", "createdByRoutineId", "createdByRunId" FROM "mail_messages"`);
        await queryRunner.query(`DROP TABLE "mail_messages"`);
        await queryRunner.query(`ALTER TABLE "temporary_mail_messages" RENAME TO "mail_messages"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9236dc41f28e0328f85094c8e4" ON "mail_messages" ("accountId", "gmailMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f56c2d83926c46deb50857d3f" ON "mail_messages" ("threadId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d1e1ed9661e19183e183f4828" ON "mail_messages" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c04d6a0d2725d48bbbeb2b136f" ON "mail_messages" ("accountId", "providerLocation") `);
        await queryRunner.query(`CREATE INDEX "IDX_7524de71140222c20b8f0ea341" ON "mail_messages" ("accountId", "gmailThreadId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_7524de71140222c20b8f0ea341"`);
        await queryRunner.query(`DROP INDEX "IDX_c04d6a0d2725d48bbbeb2b136f"`);
        await queryRunner.query(`DROP INDEX "IDX_9d1e1ed9661e19183e183f4828"`);
        await queryRunner.query(`DROP INDEX "IDX_2f56c2d83926c46deb50857d3f"`);
        await queryRunner.query(`DROP INDEX "IDX_9236dc41f28e0328f85094c8e4"`);
        await queryRunner.query(`ALTER TABLE "mail_messages" RENAME TO "temporary_mail_messages"`);
        await queryRunner.query(`CREATE TABLE "mail_messages" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "accountId" varchar NOT NULL, "threadId" varchar NOT NULL, "gmailMessageId" varchar NOT NULL, "gmailThreadId" varchar NOT NULL, "gmailDraftId" varchar NOT NULL DEFAULT (''), "fromName" varchar NOT NULL DEFAULT (''), "fromEmail" varchar NOT NULL DEFAULT (''), "toEmails" text NOT NULL DEFAULT (''), "ccEmails" text NOT NULL DEFAULT (''), "bccEmails" text NOT NULL DEFAULT (''), "subject" varchar NOT NULL DEFAULT (''), "snippet" text NOT NULL DEFAULT (''), "bodyText" text NOT NULL DEFAULT (''), "bodyHtml" text NOT NULL DEFAULT (''), "labelIds" text NOT NULL DEFAULT (''), "sentAt" datetime, "messageIdHeader" varchar NOT NULL DEFAULT (''), "referencesHeader" text NOT NULL DEFAULT (''), "inReplyToHeader" varchar NOT NULL DEFAULT (''), "attachmentsJson" text NOT NULL DEFAULT ('[]'), "sizeEstimate" integer NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "createdByUserId" varchar, "createdByEmployeeId" varchar, "createdByRoutineId" varchar, "createdByRunId" varchar)`);
        await queryRunner.query(`INSERT INTO "mail_messages"("id", "companyId", "accountId", "threadId", "gmailMessageId", "gmailThreadId", "gmailDraftId", "fromName", "fromEmail", "toEmails", "ccEmails", "bccEmails", "subject", "snippet", "bodyText", "bodyHtml", "labelIds", "sentAt", "messageIdHeader", "referencesHeader", "inReplyToHeader", "attachmentsJson", "sizeEstimate", "createdAt", "updatedAt", "createdByUserId", "createdByEmployeeId", "createdByRoutineId", "createdByRunId") SELECT "id", "companyId", "accountId", "threadId", "gmailMessageId", "gmailThreadId", "gmailDraftId", "fromName", "fromEmail", "toEmails", "ccEmails", "bccEmails", "subject", "snippet", "bodyText", "bodyHtml", "labelIds", "sentAt", "messageIdHeader", "referencesHeader", "inReplyToHeader", "attachmentsJson", "sizeEstimate", "createdAt", "updatedAt", "createdByUserId", "createdByEmployeeId", "createdByRoutineId", "createdByRunId" FROM "temporary_mail_messages"`);
        await queryRunner.query(`DROP TABLE "temporary_mail_messages"`);
        await queryRunner.query(`CREATE INDEX "IDX_9d1e1ed9661e19183e183f4828" ON "mail_messages" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f56c2d83926c46deb50857d3f" ON "mail_messages" ("threadId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9236dc41f28e0328f85094c8e4" ON "mail_messages" ("accountId", "gmailMessageId") `);
        await queryRunner.query(`DROP INDEX "IDX_d30a1e4d808dccb9b90ea431aa"`);
        await queryRunner.query(`DROP INDEX "IDX_e14ce68c3b10e0c7a6d5e5ef4c"`);
        await queryRunner.query(`ALTER TABLE "mail_accounts" RENAME TO "temporary_mail_accounts"`);
        await queryRunner.query(`CREATE TABLE "mail_accounts" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "connectionId" varchar NOT NULL, "address" varchar NOT NULL, "status" varchar NOT NULL DEFAULT ('active'), "statusMessage" varchar NOT NULL DEFAULT (''), "historyId" varchar NOT NULL DEFAULT (''), "lastSyncAt" datetime, "backfilledAt" datetime, "backfillPageToken" varchar NOT NULL DEFAULT (''), "backfilledCount" integer NOT NULL DEFAULT (0), "createdByUserId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "syncState" varchar NOT NULL DEFAULT ('idle'), "syncAttemptId" varchar, "syncStartedAt" datetime, "syncFinishedAt" datetime, "aiAnalysisEnabled" boolean NOT NULL DEFAULT (1), "aiAnalysisEmployeeId" varchar, "aiAnalysisModelId" varchar)`);
        await queryRunner.query(`INSERT INTO "mail_accounts"("id", "companyId", "connectionId", "address", "status", "statusMessage", "historyId", "lastSyncAt", "backfilledAt", "backfillPageToken", "backfilledCount", "createdByUserId", "createdAt", "updatedAt", "syncState", "syncAttemptId", "syncStartedAt", "syncFinishedAt", "aiAnalysisEnabled", "aiAnalysisEmployeeId", "aiAnalysisModelId") SELECT "id", "companyId", "connectionId", "address", "status", "statusMessage", "historyId", "lastSyncAt", "backfilledAt", "backfillPageToken", "backfilledCount", "createdByUserId", "createdAt", "updatedAt", "syncState", "syncAttemptId", "syncStartedAt", "syncFinishedAt", "aiAnalysisEnabled", "aiAnalysisEmployeeId", "aiAnalysisModelId" FROM "temporary_mail_accounts"`);
        await queryRunner.query(`DROP TABLE "temporary_mail_accounts"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d30a1e4d808dccb9b90ea431aa" ON "mail_accounts" ("connectionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e14ce68c3b10e0c7a6d5e5ef4c" ON "mail_accounts" ("companyId") `);
    }

}
