import { MigrationInterface, QueryRunner } from "typeorm";

export class RoutineSelfReviewScope1788874751311 implements MigrationInterface {
    name = 'RoutineSelfReviewScope1788874751311'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_ef3c194cfdbf720e71464a3b30"`);
        await queryRunner.query(`DROP INDEX "IDX_59e11503010aeeab1de06f89a9"`);
        await queryRunner.query(`CREATE TABLE "temporary_routines" ("id" varchar PRIMARY KEY NOT NULL, "employeeId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "cronExpr" varchar NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "lastRunAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "timeoutSec" integer NOT NULL DEFAULT (3600), "requiresApproval" boolean NOT NULL DEFAULT (0), "webhookEnabled" boolean NOT NULL DEFAULT (0), "webhookToken" varchar, "body" text NOT NULL DEFAULT (''), "nextRunAt" datetime, "browserEnabledOverride" boolean, "modelId" varchar, "catchUpPolicy" varchar NOT NULL DEFAULT ('once'), "maxAttempts" integer NOT NULL DEFAULT (1), "retryBackoffSec" integer NOT NULL DEFAULT (60), "retryOnTimeout" boolean NOT NULL DEFAULT (0), "memberBrowserId" varchar, "folderId" varchar, "acceptanceCriteria" text NOT NULL DEFAULT (''), "goalId" varchar, "consecutiveFailures" integer NOT NULL DEFAULT (0), "mailDeliveryMode" varchar, "selfReviewOnly" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "temporary_routines"("id", "employeeId", "name", "slug", "cronExpr", "enabled", "lastRunAt", "createdAt", "timeoutSec", "requiresApproval", "webhookEnabled", "webhookToken", "body", "nextRunAt", "browserEnabledOverride", "modelId", "catchUpPolicy", "maxAttempts", "retryBackoffSec", "retryOnTimeout", "memberBrowserId", "folderId", "acceptanceCriteria", "goalId", "consecutiveFailures", "mailDeliveryMode") SELECT "id", "employeeId", "name", "slug", "cronExpr", "enabled", "lastRunAt", "createdAt", "timeoutSec", "requiresApproval", "webhookEnabled", "webhookToken", "body", "nextRunAt", "browserEnabledOverride", "modelId", "catchUpPolicy", "maxAttempts", "retryBackoffSec", "retryOnTimeout", "memberBrowserId", "folderId", "acceptanceCriteria", "goalId", "consecutiveFailures", "mailDeliveryMode" FROM "routines"`);
        await queryRunner.query(`DROP TABLE "routines"`);
        await queryRunner.query(`ALTER TABLE "temporary_routines" RENAME TO "routines"`);
        await queryRunner.query(`CREATE INDEX "IDX_ef3c194cfdbf720e71464a3b30" ON "routines" ("enabled", "nextRunAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_59e11503010aeeab1de06f89a9" ON "routines" ("employeeId", "slug") `);
        await queryRunner.query(`DROP INDEX "IDX_27b735e6b03ac1d5e60623f720"`);
        await queryRunner.query(`CREATE TABLE "temporary_revision_proposals" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "employeeId" varchar NOT NULL, "kind" varchar NOT NULL, "targetId" varchar, "targetLabel" varchar NOT NULL DEFAULT (''), "baseBody" text NOT NULL DEFAULT (''), "proposedBody" text NOT NULL DEFAULT (''), "rationale" text NOT NULL DEFAULT (''), "evidenceRunIdsJson" text NOT NULL DEFAULT ('[]'), "status" varchar NOT NULL DEFAULT ('pending'), "errorMessage" text NOT NULL DEFAULT (''), "decidedAt" datetime, "decidedByUserId" varchar, "reviewNote" text NOT NULL DEFAULT (''), "stallRemindedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "reviewRunId" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_revision_proposals"("id", "companyId", "employeeId", "kind", "targetId", "targetLabel", "baseBody", "proposedBody", "rationale", "evidenceRunIdsJson", "status", "errorMessage", "decidedAt", "decidedByUserId", "reviewNote", "stallRemindedAt", "createdAt") SELECT "id", "companyId", "employeeId", "kind", "targetId", "targetLabel", "baseBody", "proposedBody", "rationale", "evidenceRunIdsJson", "status", "errorMessage", "decidedAt", "decidedByUserId", "reviewNote", "stallRemindedAt", "createdAt" FROM "revision_proposals"`);
        await queryRunner.query(`DROP TABLE "revision_proposals"`);
        await queryRunner.query(`ALTER TABLE "temporary_revision_proposals" RENAME TO "revision_proposals"`);
        await queryRunner.query(`CREATE INDEX "IDX_27b735e6b03ac1d5e60623f720" ON "revision_proposals" ("companyId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d02b95ff3d6b0c87d74ce85cb3" ON "revision_proposals" ("companyId", "employeeId", "reviewRunId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_d02b95ff3d6b0c87d74ce85cb3"`);
        await queryRunner.query(`DROP INDEX "IDX_27b735e6b03ac1d5e60623f720"`);
        await queryRunner.query(`ALTER TABLE "revision_proposals" RENAME TO "temporary_revision_proposals"`);
        await queryRunner.query(`CREATE TABLE "revision_proposals" ("id" varchar PRIMARY KEY NOT NULL, "companyId" varchar NOT NULL, "employeeId" varchar NOT NULL, "kind" varchar NOT NULL, "targetId" varchar, "targetLabel" varchar NOT NULL DEFAULT (''), "baseBody" text NOT NULL DEFAULT (''), "proposedBody" text NOT NULL DEFAULT (''), "rationale" text NOT NULL DEFAULT (''), "evidenceRunIdsJson" text NOT NULL DEFAULT ('[]'), "status" varchar NOT NULL DEFAULT ('pending'), "errorMessage" text NOT NULL DEFAULT (''), "decidedAt" datetime, "decidedByUserId" varchar, "reviewNote" text NOT NULL DEFAULT (''), "stallRemindedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "revision_proposals"("id", "companyId", "employeeId", "kind", "targetId", "targetLabel", "baseBody", "proposedBody", "rationale", "evidenceRunIdsJson", "status", "errorMessage", "decidedAt", "decidedByUserId", "reviewNote", "stallRemindedAt", "createdAt") SELECT "id", "companyId", "employeeId", "kind", "targetId", "targetLabel", "baseBody", "proposedBody", "rationale", "evidenceRunIdsJson", "status", "errorMessage", "decidedAt", "decidedByUserId", "reviewNote", "stallRemindedAt", "createdAt" FROM "temporary_revision_proposals"`);
        await queryRunner.query(`DROP TABLE "temporary_revision_proposals"`);
        await queryRunner.query(`CREATE INDEX "IDX_27b735e6b03ac1d5e60623f720" ON "revision_proposals" ("companyId", "status") `);
        await queryRunner.query(`DROP INDEX "IDX_59e11503010aeeab1de06f89a9"`);
        await queryRunner.query(`DROP INDEX "IDX_ef3c194cfdbf720e71464a3b30"`);
        await queryRunner.query(`ALTER TABLE "routines" RENAME TO "temporary_routines"`);
        await queryRunner.query(`CREATE TABLE "routines" ("id" varchar PRIMARY KEY NOT NULL, "employeeId" varchar NOT NULL, "name" varchar NOT NULL, "slug" varchar NOT NULL, "cronExpr" varchar NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "lastRunAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "timeoutSec" integer NOT NULL DEFAULT (3600), "requiresApproval" boolean NOT NULL DEFAULT (0), "webhookEnabled" boolean NOT NULL DEFAULT (0), "webhookToken" varchar, "body" text NOT NULL DEFAULT (''), "nextRunAt" datetime, "browserEnabledOverride" boolean, "modelId" varchar, "catchUpPolicy" varchar NOT NULL DEFAULT ('once'), "maxAttempts" integer NOT NULL DEFAULT (1), "retryBackoffSec" integer NOT NULL DEFAULT (60), "retryOnTimeout" boolean NOT NULL DEFAULT (0), "memberBrowserId" varchar, "folderId" varchar, "acceptanceCriteria" text NOT NULL DEFAULT (''), "goalId" varchar, "consecutiveFailures" integer NOT NULL DEFAULT (0), "mailDeliveryMode" varchar)`);
        await queryRunner.query(`INSERT INTO "routines"("id", "employeeId", "name", "slug", "cronExpr", "enabled", "lastRunAt", "createdAt", "timeoutSec", "requiresApproval", "webhookEnabled", "webhookToken", "body", "nextRunAt", "browserEnabledOverride", "modelId", "catchUpPolicy", "maxAttempts", "retryBackoffSec", "retryOnTimeout", "memberBrowserId", "folderId", "acceptanceCriteria", "goalId", "consecutiveFailures", "mailDeliveryMode") SELECT "id", "employeeId", "name", "slug", "cronExpr", "enabled", "lastRunAt", "createdAt", "timeoutSec", "requiresApproval", "webhookEnabled", "webhookToken", "body", "nextRunAt", "browserEnabledOverride", "modelId", "catchUpPolicy", "maxAttempts", "retryBackoffSec", "retryOnTimeout", "memberBrowserId", "folderId", "acceptanceCriteria", "goalId", "consecutiveFailures", "mailDeliveryMode" FROM "temporary_routines"`);
        await queryRunner.query(`DROP TABLE "temporary_routines"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_59e11503010aeeab1de06f89a9" ON "routines" ("employeeId", "slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef3c194cfdbf720e71464a3b30" ON "routines" ("enabled", "nextRunAt") `);
    }

}
