import {
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
} from "typeorm";

/**
 * Instance-level key/value settings persisted outside any one company. Some
 * are generated by the server (such as the Web Push VAPID keypair); others
 * are edited by a master admin (public URL, sign-up policy, SSO, and global
 * SMTP). Secrets stored here are encrypted before they reach `value`.
 */
@Entity("app_settings")
export class AppSetting {
  @PrimaryColumn({ type: "varchar" })
  key!: string;

  @Column({ type: "text" })
  value!: string;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}
