/**
 * Regenerate iOS launch images and their links in client/index.html:
 *   npx tsx scripts/icons/generate-splash.ts
 *
 * Requires local Chrome or Playwright Chromium. GENOSYN_SPLASH_BROWSER can
 * name another Chromium executable. PNGs are committed and need no browser
 * at build time. The app's Logo is rendered without network fonts, matching
 * the system-font fallback used by the production app's content policy.
 */
import { existsSync } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium, type Page } from "playwright-core";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { Logo } from "../../client/components/Logo";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const output = path.join(appRoot, "client/public/splash");
const indexPath = path.join(appRoot, "client/index.html");
const startMarker = "    <!-- iOS launch images: generated by scripts/icons/generate-splash.ts. -->";
const endMarker = "    <!-- End iOS launch images. -->";

// Portrait screen dimensions in CSS pixels and their device pixel ratio.
// These are full screens, not Safari's smaller browser viewports. Shared
// resolutions cover several generations; landscape uses the same device
// media query with an orientation condition and a transposed PNG.
// Sources: Playwright's iPhone/iPad descriptors and Apple's display sizes:
// https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/
const screens: ReadonlyArray<readonly [number, number, number]> = [
  [320, 568, 2], // iPhone SE (first generation)
  [375, 667, 2], // iPhone 6–8 and SE (second/third generation)
  [375, 812, 3], // iPhone X/XS/11 Pro and 12/13 mini
  [390, 844, 3], // iPhone 12–14
  [393, 852, 3], // iPhone 14 Pro, 15/16
  [402, 874, 3], // iPhone 16 Pro, 17/17 Pro
  [414, 736, 3], // iPhone 6–8 Plus
  [414, 896, 2], // iPhone XR/11
  [414, 896, 3], // iPhone XS Max/11 Pro Max
  [420, 912, 3], // iPhone Air
  [428, 926, 3], // iPhone 12/13 Pro Max, 14 Plus
  [430, 932, 3], // iPhone 14/15 Pro Max, 15/16 Plus
  [440, 956, 3], // iPhone 16/17 Pro Max
  [744, 1133, 2], // iPad mini (sixth generation and A17 Pro)
  [768, 1024, 2], // iPad 9.7-inch and older iPad mini
  [810, 1080, 2], // iPad 10.2-inch
  [820, 1180, 2], // iPad 10.9-inch, iPad Air 11-inch
  [834, 1112, 2], // iPad Pro/Air 10.5-inch
  [834, 1194, 2], // iPad Pro 11-inch (first–fourth generation)
  [834, 1210, 2], // iPad Pro 11-inch (M4/M5)
  [1024, 1366, 2], // iPad Pro 12.9-inch and iPad Air 13-inch
  [1032, 1376, 2], // iPad Pro 13-inch (M4/M5)
];

const executablePath = process.env.GENOSYN_SPLASH_BROWSER ?? [
  chromium.executablePath(),
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium",
  "/usr/bin/chromium-browser",
].find((candidate) => existsSync(candidate));
if (!executablePath || !existsSync(executablePath)) {
  throw new Error("Install Chrome/Chromium or set GENOSYN_SPLASH_BROWSER to its executable.");
}

const logo = renderToStaticMarkup(createElement(Logo));
const html = `<!doctype html>
<html><head><meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  html, body { margin: 0; width: 100%; height: 100%; overflow: hidden; background: #000; color: #fff; }
  body { display: flex; align-items: center; justify-content: center; }
  svg { display: block; width: 240px; max-width: calc(100% - 64px); height: auto; }
</style></head><body>${logo}</body></html>`;

await fs.mkdir(output, { recursive: true });
const links: string[] = [];
const browser = await chromium.launch({ executablePath, headless: true });
const pages = new Map<number, Page>();
try {
  for (const [width, height, scale] of screens) {
    for (const orientation of ["portrait", "landscape"] as const) {
      const viewport = orientation === "portrait"
        ? { width, height }
        : { width: height, height: width };
      let page = pages.get(scale);
      if (!page) {
        const context = await browser.newContext({ viewport, deviceScaleFactor: scale });
        page = await context.newPage();
        await page.setContent(html);
        await page.evaluate(() => document.fonts.ready);
        pages.set(scale, page);
      }
      await page.setViewportSize(viewport);
      const filename = `genosyn-${viewport.width * scale}x${viewport.height * scale}.png`;
      await page.screenshot({ path: path.join(output, filename), animations: "disabled" });
      const media = `screen and (device-width: ${width}px) and (device-height: ${height}px) and (-webkit-device-pixel-ratio: ${scale}) and (orientation: ${orientation})`;
      links.push(
        "    <link",
        '      rel="apple-touch-startup-image"',
        `      href="/splash/${filename}"`,
        `      media="${media}"`,
        "    />",
      );
    }
  }
} finally {
  await browser.close();
}

// Read at the end so regenerating assets does not overwrite concurrent edits
// elsewhere in the document. Only the generated block is replaced.
const index = await fs.readFile(indexPath, "utf8");
const block = [startMarker, ...links, endMarker].join("\n");
const start = index.indexOf(startMarker);
let updated: string;
if (start >= 0) {
  const end = index.indexOf(endMarker, start);
  if (end < 0) throw new Error("Missing end marker for iOS launch images in client/index.html.");
  updated = index.slice(0, start) + block + index.slice(end + endMarker.length);
} else {
  const iconLink = '    <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />';
  if (!index.includes(iconLink)) throw new Error("Cannot locate the Apple icon link in client/index.html.");
  updated = index.replace(iconLink, `${iconLink}\n${block}`);
}
await fs.writeFile(indexPath, updated);
console.log(`Generated ${screens.length * 2} iOS launch images and updated client/index.html.`);
